DROP FUNCTION DSS.ISACTIVATIONDATE;

CREATE OR REPLACE FUNCTION DSS.ISACTIVATIONDATE (d VARCHAR2)
   RETURN VARCHAR2
IS
   v_date   DATE;
BEGIN
   SELECT TO_DATE (SUBSTR (D, 0, 8), 'YYYYMMDD')
     INTO v_date
     FROM DUAL;

   RETURN 'Y';
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 'N';
END;
/
