DROP TRIGGER DSS.CONF_PRODUCT_RULES_TRG;

CREATE OR REPLACE TRIGGER DSS.CONF_PRODUCT_RULES_TRG
BEFORE INSERT
ON DSS.CONF_PRODUCT_RULES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := CONF_PRODUCT_RULES_SEQ.nextval;
END CONF_PRODUCT_RULES_TRG;
/
