DROP TRIGGER DSS.DSS_ROW_DELIMITER_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_ROW_DELIMITER_TRG
BEFORE INSERT
ON DSS.DSS_ROW_DELIMITER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := SEQ_ROW_DELIMITER_ID.nextval;
END DSS_ROW_DELIMITER_TRG;
/
