DROP TRIGGER DSS.DSS_ORDER_SCAN_LINES_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_ORDER_SCAN_LINES_TRG
   BEFORE INSERT
   ON DSS.DSS_ORDER_SCAN_LINES
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad: Highlight column LINEID
   IF :new.LINEID IS NULL
   THEN
      :new.LINEID := SEQ_ORDER_SCAN_LINEID.NEXTVAL;
   END IF;
END DSS_ORDER_SCAN_LINES_TRG;
/
