DROP TRIGGER DSS.DSS_SERIALS_MASTER_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_SERIALS_MASTER_TRG
   BEFORE INSERT
   ON DSS.DSS_SERIALS_MASTER
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column ROWSEQ
   :new.ROWSEQ := SEQ_DSS_SERIALS_MASTER.NEXTVAL;
END DSS_SERIALS_MASTER_TRG;
/
