DROP TRIGGER DSS.DSS_ORDER_SCAN_SERIALS2_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_ORDER_SCAN_SERIALS2_TRG
BEFORE INSERT
ON DSS.DSS_ORDER_SCAN_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
   :new.SCANID := SEQ_ORDER_SCAN_SER.nextval;
END DSS_ORDER_SCAN_SERIALS2_TRG;
/
