DROP TRIGGER DSS.DSS_ORDER_SERIALS_TEMP_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_ORDER_SERIALS_TEMP_TRG
BEFORE INSERT
ON DSS.DSS_ORDER_SERIALS_TEMP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SCANID
  :new.SCANID := DSS_ORDER_SERIALS_TEMP_SEQ.nextval;
END DSS_ORDER_SERIALS_TEMP_TRG;
/
