DROP TRIGGER DSS.DSS_FILES_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_FILES_TRG
BEFORE INSERT
ON DSS.DSS_FILES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_FILES_SEQ.nextval;
END DSS_FILES_TRG;
/
