DROP TRIGGER DSS.DSS_WARRANTY_MASTER_BK_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_WARRANTY_MASTER_BK_TRG
BEFORE INSERT
ON DSS.DSS_WARRANTY_MASTER_BK
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := DSS_WARRANTY_MASTER_BK_SEQ.nextval;
END DSS_WARRANTY_MASTER_BK_TRG;
/
