DROP TRIGGER DSS.DSS_ACTIVATION_SERIAL_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_ACTIVATION_SERIAL_TRG
BEFORE INSERT
ON DSS.DSS_ACTIVATION_SERIAL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_ACTIVATION_SERIAL_SEQ.nextval;
END DSS_ACTIVATION_SERIAL_TRG;
/
