DROP TRIGGER DSS.DSS_BULK_SCAN_CONFIG_TRG1;

CREATE OR REPLACE TRIGGER DSS.DSS_BULK_SCAN_CONFIG_TRG1
BEFORE INSERT
ON DSS.DSS_BULK_SCAN_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE 
BEGIN  
   :new.SEQNO := SEQ_BULK_SCAN_CONFIG.NEXTVAL;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/
