DROP TRIGGER DSS.DSS_FILE_SERIALS_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_FILE_SERIALS_TRG
BEFORE INSERT
ON DSS.DSS_FILE_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_FILE_SERIALS_SEQ.nextval;
END DSS_FILE_SERIALS_TRG;
/
