DROP TRIGGER DSS.DSS_SALES_UPLD_DTL_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_SALES_UPLD_DTL_TRG
BEFORE INSERT
ON DSS.DSS_SALES_UPLD_DTL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINESEQ
  :new.LINESEQ := SEQ_SALES_UPLD_DTL.nextval;
END DSS_SALES_UPLD_DTL_TRG;
/
