DROP TRIGGER DSS.DSS_STOCK_COUNT_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_STOCK_COUNT_TRG
BEFORE INSERT
ON DSS.DSS_STOCK_COUNT
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROW_SEQ
  :new.ROW_SEQ := DSS_STOCK_COUNT_SEQ.nextval;
END DSS_STOCK_COUNT_TRG;
/
