DROP TRIGGER DSS.DSS_PRODUCTS_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_PRODUCTS_TRG
BEFORE INSERT
ON DSS.DSS_PRODUCTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := SEQ_DSS_PRODUCTS_ID.nextval;
END DSS_PRODUCTS_TRG;
/
