DROP TRIGGER DSS.DSS_SERIALS_ANALYSIS_TRG;

CREATE OR REPLACE TRIGGER DSS.DSS_SERIALS_ANALYSIS_TRG
BEFORE INSERT
ON DSS.DSS_SERIALS_ANALYSIS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := DSS_SERIALS_ANALYSIS_SEQ.nextval;
END DSS_SERIALS_ANALYSIS_TRG;
/
