DROP TRIGGER DSS.INTM_CATEGORY_VALIDATION_TRG;

CREATE OR REPLACE TRIGGER DSS.INTM_CATEGORY_VALIDATION_TRG
BEFORE INSERT
ON DSS.INTM_CATEGORY_VALIDATION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := SEQ_CATEGORY_VALIDATION.nextval;
END INTM_CATEGORY_VALIDATION_TRG;
/
