DROP TRIGGER DSS.LABEL_COUNTER_TRG;

CREATE OR REPLACE TRIGGER DSS.LABEL_COUNTER_TRG
BEFORE INSERT
ON DSS.LABEL_COUNTER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := LABEL_COUNTER2_SEQ.nextval;
END LABEL_COUNTER_TRG;
/
