DROP TRIGGER DSS.PAYOUT_IMEI_VALIDATION_TRG;

CREATE OR REPLACE TRIGGER DSS.PAYOUT_IMEI_VALIDATION_TRG
BEFORE INSERT
ON DSS.PAYOUT_IMEI_VALIDATION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := PAYOUT_IMEI_SEQ.nextval;
END PAYOUT_IMEI_VALIDATION_TRG;
/
