DROP TRIGGER DSS.REP_CONNECTIONS_TRG;

CREATE OR REPLACE TRIGGER DSS.REP_CONNECTIONS_TRG
BEFORE INSERT
ON DSS.REP_CONNECTIONS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := REP_CONNECTIONS_SEQ.nextval;
END REP_CONNECTIONS_TRG;
/
