DROP TRIGGER DSS.RPT_SCAN_ITEM_LEVEL_TRG;

CREATE OR REPLACE TRIGGER DSS.RPT_SCAN_ITEM_LEVEL_TRG
BEFORE INSERT
ON DSS.RPT_SCAN_ITEM_LEVEL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := RPT_SCAN_ITEM_LEVEL_SEQ.nextval;
END RPT_SCAN_ITEM_LEVEL_TRG;
/
