DROP TRIGGER DSS.SHOPPER_API_EVENTS_TRG;

CREATE OR REPLACE TRIGGER DSS.SHOPPER_API_EVENTS_TRG
   BEFORE INSERT
   ON DSS.SHOPPER_API_EVENTS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column EVENTID
   :new.ROWSEQ := SHOPPER_API_EVENTS_SEQ.NEXTVAL;
---:new.EVENTID := :new.rowseq;
END SHOPPER_API_EVENTS_TRG;
/
