DROP TRIGGER DSS.SHOPPER_API_SHOPS_TRG;

CREATE OR REPLACE TRIGGER DSS.SHOPPER_API_SHOPS_TRG
   BEFORE INSERT
   ON DSS.SHOPPER_API_SHOPS
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column ROWSEQ
   :new.ROWSEQ := SHOPPER_API_SHOPS_SEQ.NEXTVAL;
END SHOPPER_API_SHOPS_TRG;
/
