DROP TRIGGER DSS.TEMP_ACTIVATION_SERIALS_TRG;

CREATE OR REPLACE TRIGGER DSS.TEMP_ACTIVATION_SERIALS_TRG
BEFORE INSERT
ON DSS.TEMP_ACTIVATION_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_ACTIVATION_SERIALS_SEQ.nextval;
END TEMP_ACTIVATION_SERIALS_TRG;
/
