DROP TRIGGER DSS.TEMP_IMEI_TRG;

CREATE OR REPLACE TRIGGER DSS.TEMP_IMEI_TRG
BEFORE INSERT
ON DSS.TEMP_IMEI
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_IMEI_SEQ.nextval;
END TEMP_IMEI_TRG;
/
