DROP TRIGGER DSS.TEMP_SAM_PO_LINES_TRG;

CREATE OR REPLACE TRIGGER DSS.TEMP_SAM_PO_LINES_TRG
BEFORE INSERT
ON DSS.TEMP_SAM_PO_LINES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_SAM_PO_LINES_SEQ.nextval;
END TEMP_SAM_PO_LINES_TRG;
/
