DROP TRIGGER DSS.TK_ORDER_SCAN_CONFIG_TRG;

CREATE OR REPLACE TRIGGER DSS.TK_ORDER_SCAN_CONFIG_TRG
BEFORE INSERT
ON DSS.TK_ORDER_SCAN_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINE_SEQ
  :new.LINE_SEQ := SEQ_ORDER_SCAN_CONFIG.nextval;
END TK_ORDER_SCAN_CONFIG_TRG;
/
