DROP VIEW DSS.V_DSS_MS_SUB_CATEGORIES;

CREATE OR REPLACE FORCE VIEW DSS.V_DSS_MS_SUB_CATEGORIES
(
    ID
   ,DESCRIPTION
   ,LAST_UPDATE_DATE
)
AS
    SELECT FLEX_VALUE_MEANING ID, DESCRIPTION, LAST_UPDATE_DATE
    FROM SYN_FLEX_VALUES
    WHERE FLEX_VALUE_SET_ID = 1009639;


GRANT SELECT ON DSS.V_DSS_MS_SUB_CATEGORIES TO SELDATA;
