DROP VIEW DSS.V_DSS_MS_CATEGORIES;

CREATE OR REPLACE FORCE VIEW DSS.V_DSS_MS_CATEGORIES
(
    ID
   ,DESCRIPTION
   ,LAST_UPDATE_DATE
)
AS
    SELECT FLEX_VALUE_MEANING ID, DESCRIPTION, LAST_UPDATE_DATE
    FROM SYN_FLEX_VALUES
    WHERE FLEX_VALUE_SET_ID = 1009638;


GRANT SELECT ON DSS.V_DSS_MS_CATEGORIES TO SELDATA;
