DROP VIEW DSS.V_PROCEDURE_PARAMETERS;

CREATE OR REPLACE FORCE VIEW DSS.V_PROCEDURE_PARAMETERS
(
    PACKAGE_NAME
   ,PROCEDURENAME
   ,POSITION
   ,PARAM_NAME
   ,DATA_TYPE
   ,DATA_LENGTH
   ,IN_OUT
)
AS
    SELECT PACKAGE_NAME
          ,OBJECT_NAME PROCEDURENAME
          ,POSITION
          ,ARGUMENT_NAME PARAM_NAME
          ,DATA_TYPE
          ,DATA_LENGTH
          ,IN_OUT
    FROM USER_ARGUMENTS;


GRANT SELECT ON DSS.V_PROCEDURE_PARAMETERS TO SELDATA;
