DROP INDEX DSS.AR_ORDER_SCAN_SERIALS_L010;

CREATE INDEX DSS.AR_ORDER_SCAN_SERIALS_L010 ON DSS.AR_ORDER_SCAN_SERIALS
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
