DROP INDEX DSS.AR_ORDER_SCAN_LINES_X01;

CREATE INDEX DSS.AR_ORDER_SCAN_LINES_X01 ON DSS.AR_ORDER_SCAN_LINES
(ORDER_TYPE, ORDER_NUMBER, ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
