DROP INDEX DSS.AR_ORDER_SCAN_HEADER_U01;

CREATE UNIQUE INDEX DSS.AR_ORDER_SCAN_HEADER_U01 ON DSS.AR_ORDER_SCAN_HEADER
(SCR_ORGANIZATION_ID, ORDER_NUMBER, ORDER_TYPE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
