DROP INDEX DSS.DSS_ORDER_SCAN_SERIALS_U201;

CREATE UNIQUE INDEX DSS.DSS_ORDER_SCAN_SERIALS_U201 ON DSS.DSS_ORDER_SCAN_SERIALS
(LINEID, SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
