DROP INDEX DSS.DSS_API_SERIALS_U01;

CREATE UNIQUE INDEX DSS.DSS_API_SERIALS_U01 ON DSS.DSS_API_SERIALS
(COLUMNINDEX, SEQINDEX, LINEID, BATCHID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
