DROP INDEX DSS.DSS_LOCATION_MASTER_PK;

CREATE UNIQUE INDEX DSS.DSS_LOCATION_MASTER_PK ON DSS.DSS_LOCATIONS
(LOCATION_CODE, ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
