DROP INDEX DSS.DSS_MANUAL_SCAN_LINES_PK;

CREATE UNIQUE INDEX DSS.DSS_MANUAL_SCAN_LINES_PK ON DSS.DSS_MANUAL_SCAN_LINES
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
