DROP INDEX DSS.DSS_DU_UPLD_SRC_PK;

CREATE UNIQUE INDEX DSS.DSS_DU_UPLD_SRC_PK ON DSS.DSS_DU_UPLD_SRC
(ROW_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
