DROP INDEX DSS.DSS_MANIFEST_PRINT_INFO_IX23;

CREATE INDEX DSS.DSS_MANIFEST_PRINT_INFO_IX23 ON DSS.DSS_MANIFEST_PRINT_INFO
(SEAL_NUMBER)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
