DROP INDEX DSS.DSS_ACTIVATION_SERIAL_LOG_IND1;

CREATE INDEX DSS.DSS_ACTIVATION_SERIAL_LOG_IND1 ON DSS.DSS_ACTIVATION_SERIAL_LOG
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
