DROP INDEX DSS.DSS_SERIALS_CHILD_IX1;

CREATE INDEX DSS.DSS_SERIALS_CHILD_IX1 ON DSS.DSS_SERIALS_CHILD
(PARENTKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
