DROP INDEX DSS.DSS_CONSIG_INV_LINES_PK;

CREATE UNIQUE INDEX DSS.DSS_CONSIG_INV_LINES_PK ON DSS.DSS_CONSIG_INV_LINES
(LINE_NO, ORDER_TYPE, ORDER_NUMBER, ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
