DROP INDEX DSS.DSS_ORDER_SCAN_PERFORMANCE_PK;

CREATE UNIQUE INDEX DSS.DSS_ORDER_SCAN_PERFORMANCE_PK ON DSS.DSS_ORDER_SCAN_PERFORMANCE
(SEQNO)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
