DROP INDEX DSS.DSS_PRODUCTS_IX3;

CREATE INDEX DSS.DSS_PRODUCTS_IX3 ON DSS.DSS_PRODUCTS
(OPERATING_UNIT, ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
