DROP INDEX DSS.DSS_SERIALS_ANALYSIS_XI1;

CREATE INDEX DSS.DSS_SERIALS_ANALYSIS_XI1 ON DSS.DSS_SERIALS_ANALYSIS
(INVENTORY_ITEM_ID, PRODUCT_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
