DROP INDEX DSS.DSS_OPERATING_UNIT_MASTER_PK;

CREATE UNIQUE INDEX DSS.DSS_OPERATING_UNIT_MASTER_PK ON DSS.DSS_OPERATING_UNITS
(OPERATING_UNIT)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
