DROP INDEX DSS.DSS_LOG_OER_CONFIG_PK;

CREATE UNIQUE INDEX DSS.DSS_LOG_OER_CONFIG_PK ON DSS.DSS_LOG_OER_CONFIG
(LOGID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
