DROP INDEX DSS.IDX_FLS_PARENTKEY;

CREATE INDEX DSS.IDX_FLS_PARENTKEY ON DSS.DSS_FILE_SERIALS
(PARENTKEY)
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
LOCAL (  
  PARTITION P_FLS_2018
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2018_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2019
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2019_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2020
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2020_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2021
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2021_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2022
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2022_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2023
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2023_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2024
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2024_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2025
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2025_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2100
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2100_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_OTH
     TABLESPACE AXM_TS_WMS )
);
