DROP INDEX DSS.INTM_PRODUCTS_VALIDATION_PK;

CREATE UNIQUE INDEX DSS.INTM_PRODUCTS_VALIDATION_PK ON DSS.INTM_PRODUCTS_VALIDATION
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
