DROP INDEX DSS.INTM_CATEGORY_VALIDATION_PK;

CREATE UNIQUE INDEX DSS.INTM_CATEGORY_VALIDATION_PK ON DSS.INTM_CATEGORY_VALIDATION
(CATEGORY_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
