DROP INDEX DSS.LABEL_COUNTER;

CREATE UNIQUE INDEX DSS.LABEL_COUNTER ON DSS.LABEL_COUNTER
(TYPE_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
