DROP INDEX DSS.OL_ORDER_SCAN_SERIALS_X7;

CREATE INDEX DSS.OL_ORDER_SCAN_SERIALS_X7 ON DSS.OFFLINE_ORDER_SCAN_SERIALS
(JOBID, LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
