DROP INDEX DSS.PAYOUT_IMEI_VALIDATION_PK;

CREATE UNIQUE INDEX DSS.PAYOUT_IMEI_VALIDATION_PK ON DSS.PAYOUT_IMEI_VALIDATION
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
