DROP INDEX DSS.PK_DSS_ROWSEQ;

CREATE UNIQUE INDEX DSS.PK_DSS_ROWSEQ ON DSS.DSS_SERIALS_MASTER
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
