DROP INDEX DSS.PK_ROWSEQ;

CREATE UNIQUE INDEX DSS.PK_ROWSEQ ON DSS.DSS_FILE_SERIALS
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
