DROP INDEX DSS.REC_ORDER_SCAN_SERIALS_X2;

CREATE INDEX DSS.REC_ORDER_SCAN_SERIALS_X2 ON DSS.REC_ORDER_SCAN_SERIALS
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
