DROP INDEX DSS.RPT_SCAN_ITEM_LEVEL_PK;

CREATE UNIQUE INDEX DSS.RPT_SCAN_ITEM_LEVEL_PK ON DSS.RPT_SCAN_ITEM_LEVEL
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
