DROP INDEX DSS.RPT_SCAN_CONFIG_PK;

CREATE UNIQUE INDEX DSS.RPT_SCAN_CONFIG_PK ON DSS.RPT_SCAN_CONFIG
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
