DROP INDEX DSS.SEC_APPLICATION_FORMS_PK;

CREATE UNIQUE INDEX DSS.SEC_APPLICATION_FORMS_PK ON DSS.SEC_APPLICATION_FORMS
(FORM_ID)
LOGGING
TABLESPACE TS_ORABRIDGE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
