DROP INDEX DSS.SEC_APPLICATION_FORMS_U01;

CREATE UNIQUE INDEX DSS.SEC_APPLICATION_FORMS_U01 ON DSS.SEC_APPLICATION_FORMS
(FULL_NAME)
LOGGING
TABLESPACE TS_ORABRIDGE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
