DROP INDEX DSS.TEMP_IMEI_PK;

CREATE UNIQUE INDEX DSS.TEMP_IMEI_PK ON DSS.TEMP_IMEI
(ROWSEQ, SERIALNUMBER)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
