DROP INDEX DSS.TK_CATEGORIES_CONFIG_U01;

CREATE UNIQUE INDEX DSS.TK_CATEGORIES_CONFIG_U01 ON DSS.TK_CATEGORIES_CONFIG
(PURCHASETYPE, SUB_SUB_CATEGORY_CODE, SUB_CATEGORY_CODE, CATEGORY_CODE, BRAND)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
