DROP INDEX DSS.TK_CATEGORIES_CONFIG_IX2;

CREATE INDEX DSS.TK_CATEGORIES_CONFIG_IX2 ON DSS.TK_CATEGORIES_CONFIG
(CATEGORY_ID, CATEGORY_CODE, SUB_CATEGORY_CODE, SUB_SUB_CATEGORY_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
