DROP INDEX DSS.UK_FLS_SERIALKEY;

CREATE UNIQUE INDEX DSS.UK_FLS_SERIALKEY ON DSS.DSS_FILE_SERIALS
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
