DROP INDEX DSS.UQ_DSS_SERIALS_MASTER;

CREATE UNIQUE INDEX DSS.UQ_DSS_SERIALS_MASTER ON DSS.DSS_SERIALS_MASTER
(SERIALKEY, PRODUCT_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
