ALTER TABLE DSS.AR_ORDER_SCAN_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.AR_ORDER_SCAN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.AR_ORDER_SCAN_HEADER
(
  JOBID                 NUMBER,
  APP_SOURCE            VARCHAR2(30 BYTE),
  ORDER_TYPE            VARCHAR2(20 BYTE),
  ORDER_NUMBER          VARCHAR2(100 BYTE),
  ORDER_REF_NO          NUMBER,
  ORDER_REF_NO2         VARCHAR2(100 BYTE),
  ORDER_DATE            DATE,
  ORDER_REMARKS         VARCHAR2(500 BYTE),
  WARRANTY_YN           VARCHAR2(1 BYTE),
  WMS_YN                VARCHAR2(1 BYTE),
  INTERNAL_YN           VARCHAR2(1 BYTE),
  SCR_TYPE              VARCHAR2(30 BYTE),
  SCR_REF_NUMBER        NUMBER,
  SCR_REF_CODE          VARCHAR2(100 BYTE),
  SCR_OPREATING_UNIT    NUMBER,
  SCR_ORGANIZATION_ID   NUMBER,
  SCR_LOCATION_CODE     VARCHAR2(30 BYTE),
  DEST_TYPE             VARCHAR2(30 BYTE),
  DEST_REF_NUMBER       NUMBER,
  DEST_REF_CODE         VARCHAR2(100 BYTE),
  DEST_OPREATING_UNIT   NUMBER,
  DEST_ORGANIZATION_ID  NUMBER,
  DEST_LOCATION_CODE    VARCHAR2(30 BYTE),
  CREATE_DATE           DATE                    DEFAULT SYSDATE,
  MODIFY_DATE           DATE                    DEFAULT SYSDATE,
  CREATE_BY             VARCHAR2(30 BYTE),
  MODIFY_BY             VARCHAR2(30 BYTE),
  EXPIRY_DATE           DATE                    DEFAULT SYSDATE,
  EXPIRY_AFTER          NUMBER                  DEFAULT 0,
  EDITABLE_YN           VARCHAR2(1 BYTE)        DEFAULT 'Y',
  ARCHIVED_YN           VARCHAR2(1 BYTE)        DEFAULT 'N',
  ACTIVE_YN             VARCHAR2(1 BYTE)        DEFAULT 'N',
  STATUS_YN             VARCHAR2(1 BYTE)        DEFAULT 'N',
  ATTRIBUTE1            VARCHAR2(100 BYTE),
  ATTRIBUTE2            VARCHAR2(100 BYTE),
  ATTRIBUTE3            VARCHAR2(100 BYTE),
  ATTRIBUTE4            VARCHAR2(100 BYTE),
  ATTRIBUTE5            VARCHAR2(100 BYTE),
  ATTRIBUTE6            VARCHAR2(100 BYTE),
  ATTRIBUTE7            VARCHAR2(100 BYTE),
  ATTRIBUTE8            VARCHAR2(100 BYTE),
  ATTRIBUTE9            VARCHAR2(100 BYTE),
  ATTRIBUTE10           VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION AR_ORDERHEADER_2009 VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2010 VALUES LESS THAN (TO_DATE(' 2011-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2011 VALUES LESS THAN (TO_DATE(' 2012-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2012 VALUES LESS THAN (TO_DATE(' 2013-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2013 VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2014 VALUES LESS THAN (TO_DATE(' 2015-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2015 VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2016 VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2017 VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2018 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2019 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2020 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_2021 VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION AR_ORDERHEADER_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.AR_ORDER_SCAN_HEADER_PK ON DSS.AR_ORDER_SCAN_HEADER
(JOBID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.AR_ORDER_SCAN_HEADER_U01 ON DSS.AR_ORDER_SCAN_HEADER
(SCR_ORGANIZATION_ID, ORDER_NUMBER, ORDER_TYPE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.AR_ORDER_SCAN_HEADER_XD ON DSS.AR_ORDER_SCAN_HEADER
(TRUNC("ORDER_DATE"))
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.AR_ORDER_SCAN_HEADER ADD (
  CONSTRAINT AR_ORDER_SCAN_HEADER_PK
  PRIMARY KEY
  (JOBID)
  USING INDEX DSS.AR_ORDER_SCAN_HEADER_PK
  ENABLE VALIDATE,
  CONSTRAINT AR_ORDER_SCAN_HEADER_U01
  UNIQUE (SCR_ORGANIZATION_ID, ORDER_NUMBER, ORDER_TYPE)
  USING INDEX DSS.AR_ORDER_SCAN_HEADER_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.AR_ORDER_SCAN_HEADER TO SELDATA;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DSS.AR_ORDER_SCAN_HEADER TO XXWMS;
