DROP TABLE DSS.CONF_VALIDATION_KEYS CASCADE CONSTRAINTS;

CREATE TABLE DSS.CONF_VALIDATION_KEYS
(
  ROWSEQ         NUMBER,
  RULEID         NUMBER                         NOT NULL,
  KEYID          NUMBER                         NOT NULL,
  KEYNAME        VARCHAR2(100 BYTE),
  UNIQUE_KEY     INTEGER,
  NUMERIC_KEY    INTEGER,
  MAX_LENGTH     NUMBER,
  MIN_LENGTH     NUMBER,
  LUHN_KEY       INTEGER,
  SPECIAL_CHARS  INTEGER,
  CAPTURE        INTEGER,
  CREATE_DATE    DATE                           DEFAULT SYSDATE,
  MODIFY_DATE    DATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER DSS.CONF_VALIDATION_KEYS_TRG
BEFORE INSERT
ON DSS.CONF_VALIDATION_KEYS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := CONF_VALIDATION_KEYS_SEQ.nextval;
END CONF_VALIDATION_KEYS_TRG;
/
