DROP TABLE DSS.CONF_VALIDATION_RULES CASCADE CONSTRAINTS;

CREATE TABLE DSS.CONF_VALIDATION_RULES
(
  ROWSEQ           NUMBER,
  RULEID           NUMBER,
  RULE_NAME        VARCHAR2(100 BYTE),
  RULE_CODE        VARCHAR2(50 BYTE),
  RULE_PARAMETERS  VARCHAR2(500 BYTE),
  CONFIG_TYPE      VARCHAR2(50 BYTE)            DEFAULT 'CATEGORY',
  SCAN_REQUIRED    CHAR(1 BYTE)                 DEFAULT 'N'
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER DSS.CONF_VALIDATION_RULES_TRG
BEFORE INSERT
ON DSS.CONF_VALIDATION_RULES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := CONF_VALIDATION_RULES_SEQ.nextval;
END CONF_VALIDATION_RULES_TRG;
/
