DROP TABLE DSS.DATA_VALIDATION CASCADE CONSTRAINTS;

CREATE TABLE DSS.DATA_VALIDATION
(
  OPERATING_UNIT   NUMBER,
  ORGANIZATION_ID  NUMBER,
  LOCATION_CODE    VARCHAR2(100 BYTE),
  PRODUCT_CODE     VARCHAR2(100 BYTE),
  CUSTOMER_ID      VARCHAR2(100 BYTE),
  CUSTOMER_SIDEID  VARCHAR2(100 BYTE),
  QTY              NUMBER,
  DESCRIPTION      VARCHAR2(200 BYTE),
  OLDVALUE1        VARCHAR2(200 BYTE),
  OLDVALUE2        VARCHAR2(200 BYTE),
  STATUS           CHAR(1 BYTE),
  STATUS_MESSAGE   VARCHAR2(100 BYTE),
  RECORDS          NUMBER
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON DSS.DATA_VALIDATION TO SELDATA;
