ALTER TABLE DSS.DSS_SALES_UPLD_TEMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SALES_UPLD_TEMP CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SALES_UPLD_TEMP
(
  UPLOADID           NUMBER,
  LINEID             NUMBER,
  LINENUM            NUMBER,
  OPERATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  LOCATION_CODE      VARCHAR2(10 BYTE),
  TRANSACTION_NO     VARCHAR2(50 BYTE),
  TRANSACTION_DATE   DATE,
  TRANSACTION_TYPE   VARCHAR2(50 BYTE),
  PARTY_CODE         VARCHAR2(40 BYTE),
  PARTY_SITE_NUMBER  VARCHAR2(50 BYTE),
  REF_NO1            VARCHAR2(100 BYTE),
  REF_NO2            VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(50 BYTE),
  PRODUCT_UOM        VARCHAR2(10 BYTE),
  QTY                NUMBER(8),
  LC_PRICE           NUMBER(17,3),
  ONHAND_QTY         NUMBER(8),
  ITEM_TYPE          VARCHAR2(10 BYTE),
  STATUS             CHAR(1 BYTE)               DEFAULT 'N',
  STATUS_MESSGAE     VARCHAR2(100 BYTE),
  CREATE_DATE        DATE,
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE),
  ATTRIBUTE8         VARCHAR2(100 BYTE),
  ATTRIBUTE9         VARCHAR2(100 BYTE),
  ATTRIBUTE10        VARCHAR2(100 BYTE),
  ATTRIBUTE11        VARCHAR2(100 BYTE),
  ATTRIBUTE12        VARCHAR2(100 BYTE),
  ATTRIBUTE13        VARCHAR2(100 BYTE),
  ATTRIBUTE14        VARCHAR2(100 BYTE),
  ATTRIBUTE15        VARCHAR2(100 BYTE),
  RESATTRIBUTE1      VARCHAR2(500 BYTE),
  RESATTRIBUTE2      VARCHAR2(500 BYTE),
  RESATTRIBUTE3      VARCHAR2(500 BYTE),
  TAXSTATUS          VARCHAR2(50 BYTE),
  TAX_RATE_ID        NUMBER,
  TAX_VALUE          NUMBER,
  TAX_PERCENTAGE     NUMBER,
  TOTAL_PRICE        NUMBER
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_SALES_UPLD_TEMP_PK ON DSS.DSS_SALES_UPLD_TEMP
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SALES_UPLD_TEMP_U01 ON DSS.DSS_SALES_UPLD_TEMP
(LINENUM, UPLOADID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_SALES_UPLD_TEMP ADD (
  CONSTRAINT DSS_SALES_UPLD_TEMP_PK
  PRIMARY KEY
  (LINEID)
  USING INDEX DSS.DSS_SALES_UPLD_TEMP_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_SALES_UPLD_TEMP_U01
  UNIQUE (LINENUM, UPLOADID)
  USING INDEX DSS.DSS_SALES_UPLD_TEMP_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_SALES_UPLD_TEMP TO SELDATA;
