ALTER TABLE DSS.DSS_FILES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_FILES CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_FILES
(
  ROWSEQ         NUMBER,
  FILE_NAME      VARCHAR2(500 BYTE),
  FILE_PATH      VARCHAR2(1000 BYTE),
  BRAND          VARCHAR2(100 BYTE),
  ISARCHIVED     CHAR(1 BYTE)                   DEFAULT 'N',
  ARCHIVED_NAME  VARCHAR2(500 BYTE),
  ARCHIVED_PATH  VARCHAR2(500 BYTE),
  HAS_ERROR      CHAR(1 BYTE)                   DEFAULT 'N',
  ERROR_MESSAGE  VARCHAR2(1000 BYTE),
  CREATE_DATE    DATE                           DEFAULT sysdate,
  UPL_COUNT      NUMBER,
  INS_COUNT      NUMBER,
  FILE_TYPE      VARCHAR2(200 BYTE)             DEFAULT 'Shipment File',
  ATTRIBUTE1     VARCHAR2(100 BYTE),
  ATTRIBUTE2     VARCHAR2(100 BYTE),
  ATTRIBUTE3     VARCHAR2(100 BYTE),
  ATTRIBUTE4     VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index DSS.SYS_C00767397.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER DSS.DSS_FILES_TRG
BEFORE INSERT
ON DSS.DSS_FILES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_FILES_SEQ.nextval;
END DSS_FILES_TRG;
/


ALTER TABLE DSS.DSS_FILES ADD (
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_FILES TO SELDATA;
