ALTER TABLE DSS.DSS_LOG_BARCODES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_LOG_BARCODES CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_LOG_BARCODES
(
  LOGID              NUMBER,
  OPERATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  PRODUCT_CODE       VARCHAR2(50 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  BARCODE            VARCHAR2(100 BYTE),
  ACTION_TYPE        VARCHAR2(20 BYTE),
  REMARKS            VARCHAR2(200 BYTE),
  CREATE_BY          VARCHAR2(50 BYTE),
  CRAETE_DATE        DATE,
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE),
  ATTRIBUTE8         VARCHAR2(100 BYTE),
  ATTRIBUTE9         VARCHAR2(100 BYTE),
  ATTRIBUTE10        VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_LOG_BARCODES_PK ON DSS.DSS_LOG_BARCODES
(LOGID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_LOG_BARCODES ADD (
  CONSTRAINT DSS_LOG_BARCODES_PK
  PRIMARY KEY
  (LOGID)
  USING INDEX DSS.DSS_LOG_BARCODES_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_LOG_BARCODES TO SELDATA;
