ALTER TABLE DSS.DSS_ORGANIZATIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ORGANIZATIONS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ORGANIZATIONS
(
  OPERATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  ORGANIZATION_TYPE  VARCHAR2(10 BYTE),
  ORGANIZATION_CODE  VARCHAR2(5 BYTE),
  ORGANIZATION_NAME  VARCHAR2(200 BYTE),
  STATUS             CHAR(1 BYTE)               DEFAULT 'Y',
  ACTIVE             CHAR(1 BYTE)               DEFAULT 'A',
  CREATION_DATE      DATE,
  LAST_UPDATE_DATE   DATE,
  OPTIMIZA_ENABLED   CHAR(1 BYTE)               DEFAULT 'Y',
  ATTRIBUTE1         VARCHAR2(200 BYTE),
  ATTRIBUTE2         VARCHAR2(200 BYTE),
  ATTRIBUTE3         VARCHAR2(200 BYTE),
  ATTRIBUTE4         VARCHAR2(200 BYTE),
  ATTRIBUTE5         VARCHAR2(200 BYTE),
  ATTRIBUTE6         VARCHAR2(200 BYTE),
  ATTRIBUTE7         VARCHAR2(200 BYTE),
  ATTRIBUTE8         VARCHAR2(200 BYTE),
  ATTRIBUTE9         VARCHAR2(200 BYTE),
  ATTRIBUTE10        VARCHAR2(200 BYTE),
  INVENTORY_ENABLED  CHAR(1 BYTE),
  DISABLE_DATE       DATE,
  ADDRESS_1          NVARCHAR2(200),
  ADDRESS_2          NVARCHAR2(200),
  ADDRESS_3          NVARCHAR2(200),
  TIN_NO             NVARCHAR2(200)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ORGANIZATIONS_MASTER_PK ON DSS.DSS_ORGANIZATIONS
(ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_ORGANIZATIONS ADD (
  CONSTRAINT DSS_ORGANIZATIONS_MASTER_PK
  PRIMARY KEY
  (ORGANIZATION_ID)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  DISABLE NOVALIDATE);

GRANT SELECT ON DSS.DSS_ORGANIZATIONS TO SELDATA;
