ALTER TABLE DSS.DSS_DUPLICATED_BOMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_DUPLICATED_BOMS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_DUPLICATED_BOMS
(
  ORGANIZATION_ID   NUMBER,
  BILL_SEQUENCE_ID  NUMBER                      NOT NULL,
  ASSEMBLY_ITEM_ID  NUMBER,
  CREATE_DATE       DATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_DUPLICATED_BOMS_PK ON DSS.DSS_DUPLICATED_BOMS
(BILL_SEQUENCE_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_DUPLICATED_BOMS ADD (
  CONSTRAINT DSS_DUPLICATED_BOMS_PK
  PRIMARY KEY
  (BILL_SEQUENCE_ID)
  USING INDEX DSS.DSS_DUPLICATED_BOMS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_DUPLICATED_BOMS TO SELDATA;
