ALTER TABLE DSS.DSS_MODEL_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_MODEL_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_MODEL_MAPPING
(
  MODEL_SEQ         NUMBER(10)                  NOT NULL,
  ITEM_BRD_SEQ      NUMBER(10),
  MODEL_NAME        VARCHAR2(30 BYTE)           NOT NULL,
  MODEL_CODE        VARCHAR2(30 BYTE)           NOT NULL,
  MODEL_SHORT_DESC  VARCHAR2(30 BYTE)           NOT NULL,
  MODEL_ACTIVE      VARCHAR2(2 BYTE)            NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  LAST_UPDATE_DATE  DATE,
  VMODEL_SEQ        NUMBER(10),
  VBASE_BRAND_SEQ   NUMBER(10),
  VBRAND_SEQ        NUMBER(10),
  VBASE_MODEL_CODE  VARCHAR2(30 BYTE),
  VMODEL_CODE       VARCHAR2(30 BYTE),
  VMODEL_ACTIVE     VARCHAR2(1 BYTE),
  SOURCE            VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_MODEL_MAPPING_PK ON DSS.DSS_MODEL_MAPPING
(MODEL_SEQ, VMODEL_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_MODEL_MAPPING ADD (
  CONSTRAINT DSS_MODEL_MAPPING_PK
  PRIMARY KEY
  (MODEL_SEQ, VMODEL_SEQ)
  USING INDEX DSS.DSS_MODEL_MAPPING_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_MODEL_MAPPING TO SELDATA;
