ALTER TABLE DSS.DSS_UPLOAD_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_UPLOAD_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_UPLOAD_HEADER
(
  HEADERID       NUMBER,
  HEADER_NAME    VARCHAR2(100 BYTE),
  UPLD_TYPE      VARCHAR2(200 BYTE),
  CREATE_DATE    DATE,
  CREATE_BY      VARCHAR2(100 BYTE),
  FILE_NAME      VARCHAR2(100 BYTE),
  STATUS         VARCHAR2(100 BYTE),
  ATTRIBUTE1     VARCHAR2(100 BYTE),
  ATTRIBUTE2     VARCHAR2(100 BYTE),
  ATTRIBUTE3     VARCHAR2(100 BYTE),
  ATTRIBUTE4     VARCHAR2(100 BYTE),
  ATTRIBUTE5     VARCHAR2(100 BYTE),
  ATTRIBUTE6     VARCHAR2(100 BYTE),
  ATTRIBUTE7     VARCHAR2(100 BYTE),
  ATTRIBUTE8     VARCHAR2(100 BYTE),
  ATTRIBUTE9     VARCHAR2(100 BYTE),
  ATTRIBUTE10    VARCHAR2(100 BYTE),
  ATTRIBUTE11    VARCHAR2(100 BYTE),
  ATTRIBUTE12    VARCHAR2(100 BYTE),
  ATTRIBUTE13    VARCHAR2(100 BYTE),
  ATTRIBUTE14    VARCHAR2(100 BYTE),
  ATTRIBUTE15    VARCHAR2(100 BYTE),
  RESATTRIBUTE1  VARCHAR2(500 BYTE),
  RESATTRIBUTE2  VARCHAR2(500 BYTE),
  RESATTRIBUTE3  VARCHAR2(500 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_UPLOAD_HEADER_PK ON DSS.DSS_UPLOAD_HEADER
(HEADERID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_UPLOAD_HEADER ADD (
  CONSTRAINT DSS_UPLOAD_HEADER_PK
  PRIMARY KEY
  (HEADERID)
  USING INDEX DSS.DSS_UPLOAD_HEADER_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_UPLOAD_HEADER TO SELDATA;
