ALTER TABLE DSS.DSS_CODE_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_CODE_MASTER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_CODE_MASTER
(
  SEQNO             NUMBER                      NOT NULL,
  MAIN_CODE         NUMBER                      NOT NULL,
  SUB_CODE          NUMBER                      NOT NULL,
  PARAM             VARCHAR2(200 BYTE)          NOT NULL,
  PVALUE            VARCHAR2(500 BYTE)          NOT NULL,
  DESCRIPTION       VARCHAR2(500 BYTE),
  REMARKS           VARCHAR2(500 BYTE),
  EXAMPLES          VARCHAR2(500 BYTE),
  ISACTIVE          CHAR(1 BYTE)                NOT NULL,
  STATUS            CHAR(1 BYTE),
  CREATEBY          VARCHAR2(50 BYTE)           NOT NULL,
  CREATEDATE        DATE                        NOT NULL,
  LAST_UPDATE_BY    VARCHAR2(50 BYTE),
  LAST_UPDATE_DATE  DATE,
  ATTRIBUTE1        VARCHAR2(200 BYTE),
  ATTRIBUTE2        VARCHAR2(200 BYTE),
  ATTRIBUTE3        VARCHAR2(200 BYTE),
  ATTRIBUTE4        VARCHAR2(200 BYTE),
  ATTRIBUTE5        VARCHAR2(200 BYTE),
  ATTRIBUTE6        VARCHAR2(150 BYTE),
  ATTRIBUTE7        VARCHAR2(150 BYTE),
  ATTRIBUTE8        VARCHAR2(150 BYTE),
  ATTRIBUTE9        VARCHAR2(150 BYTE),
  ATTRIBUTE10       VARCHAR2(150 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_CODE_MASTER_PK ON DSS.DSS_CODE_MASTER
(SEQNO)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_CODE_MASTER_U01 ON DSS.DSS_CODE_MASTER
(MAIN_CODE, SUB_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_CODE_MASTER_U02 ON DSS.DSS_CODE_MASTER
(MAIN_CODE, PARAM, PVALUE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_CODE_MASTER ADD (
  CONSTRAINT DSS_CODE_MASTER_PK
  PRIMARY KEY
  (SEQNO)
  USING INDEX DSS.DSS_CODE_MASTER_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_CODE_MASTER_U01
  UNIQUE (MAIN_CODE, SUB_CODE)
  USING INDEX DSS.DSS_CODE_MASTER_U01
  ENABLE VALIDATE,
  CONSTRAINT DSS_CODE_MASTER_U02
  UNIQUE (MAIN_CODE, PARAM, PVALUE)
  USING INDEX DSS.DSS_CODE_MASTER_U02
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_CODE_MASTER TO SELDATA;
