ALTER TABLE DSS.DSS_WARRANTY_MASTER_BK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_WARRANTY_MASTER_BK CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_WARRANTY_MASTER_BK
(
  LINEID             NUMBER,
  IMEI_NUMBER        VARCHAR2(100 BYTE),
  IMEI_NUMBER2       VARCHAR2(100 BYTE),
  IMEI_NUMBER3       VARCHAR2(100 BYTE),
  IMEI_NUMBER4       VARCHAR2(100 BYTE),
  RFID_NUMBER        VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(50 BYTE),
  PRODUCT_BRAND      VARCHAR2(50 BYTE),
  PRODUCT_MODEL      VARCHAR2(50 BYTE),
  BRAND_SEQ          NUMBER,
  MODEL_SEQ          NUMBER,
  WARRANTY_SEQ       NUMBER,
  WARRANTY_CODE      VARCHAR2(50 BYTE),
  WARRANTY_END_DATE  DATE,
  JOB_REF_NO         NUMBER,
  JOB_REF_LINENO     NUMBER,
  JOB_REF_SEQNO      NUMBER,
  ORDER_TYPE         VARCHAR2(30 BYTE),
  ORDER_NUMBER       NUMBER,
  ORDER_NUMBER2      NUMBER,
  ORDER_NUMBER3      NUMBER,
  ORDER_DATE         DATE,
  OPERATION_UNIT     NUMBER,
  COUNTRY_CODE       VARCHAR2(30 BYTE),
  ORGANIZATIONID     NUMBER,
  CREATE_DATE        DATE,
  MODIFY_DATE        DATE,
  PRINTING_DATE      DATE,
  ACTION_TYPE        VARCHAR2(30 BYTE),
  STATUS             VARCHAR2(30 BYTE),
  INF_YN             VARCHAR2(15 BYTE),
  INF_DATE           DATE,
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE),
  ATTRIBUTE8         VARCHAR2(100 BYTE),
  ATTRIBUTE9         VARCHAR2(100 BYTE),
  ATTRIBUTE10        VARCHAR2(100 BYTE),
  VBRAND_SEQ         NUMBER,
  VBRAND_CODE        VARCHAR2(50 BYTE),
  VMODEL_SEQ         NUMBER,
  VMODEL_CODE        VARCHAR2(50 BYTE),
  BASE_BRAND_SEQ     NUMBER,
  BASE_BRAND_CODE    VARCHAR2(50 BYTE),
  VBASE_BRAND_SEQ    NUMBER,
  VBASE_BRAND_CODE   VARCHAR2(50 BYTE),
  BASE_MODEL_SEQ     NUMBER,
  BASE_MODEL_CODE    VARCHAR2(50 BYTE),
  VBASE_MODEL_SEQ    NUMBER,
  VBASE_MODEL_CODE   VARCHAR2(50 BYTE),
  WARRANTY_YEARS     NUMBER,
  WARRANTY_MONTHS    NUMBER,
  WARRANTY_DAYS      NUMBER,
  ACTION_COUNT       NUMBER,
  CREATE_BY          VARCHAR2(50 BYTE),
  MODIFY_BY          VARCHAR2(50 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index DSS.SYS_C00903823.
--  The object is created when the parent object is created.

--  There is no statement for index DSS.SYS_C00903824.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER DSS.DSS_WARRANTY_MASTER_BK_TRG
BEFORE INSERT
ON DSS.DSS_WARRANTY_MASTER_BK
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := DSS_WARRANTY_MASTER_BK_SEQ.nextval;
END DSS_WARRANTY_MASTER_BK_TRG;
/


ALTER TABLE DSS.DSS_WARRANTY_MASTER_BK ADD (
  PRIMARY KEY
  (LINEID)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE,
  UNIQUE (IMEI_NUMBER)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
