ALTER TABLE DSS.DSS_WARRANTY_ORG_LINK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_WARRANTY_ORG_LINK CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_WARRANTY_ORG_LINK
(
  LNK_SEQ           NUMBER,
  WARRANTY_SEQ      NUMBER,
  OPERATING_UNIT    NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  ACTIVE            CHAR(1 BYTE),
  ATTRIBUTE1        VARCHAR2(100 BYTE),
  ATTRIBUTE2        VARCHAR2(100 BYTE),
  ATTRIBUTE3        VARCHAR2(100 BYTE),
  ATTRIBUTE4        VARCHAR2(100 BYTE),
  ATTRIBUTE5        VARCHAR2(100 BYTE),
  ATTRIBUTE6        VARCHAR2(100 BYTE),
  ATTRIBUTE7        VARCHAR2(100 BYTE),
  ATTRIBUTE8        VARCHAR2(100 BYTE),
  ATTRIBUTE9        VARCHAR2(100 BYTE),
  ATTRIBUTE10       VARCHAR2(100 BYTE),
  ATTRIBUTE15       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_WARRANTY_ORG_LINK_PK ON DSS.DSS_WARRANTY_ORG_LINK
(LNK_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_WARRANTY_ORG_LINK_U01 ON DSS.DSS_WARRANTY_ORG_LINK
(OPERATING_UNIT, WARRANTY_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_WARRANTY_ORG_LINK ADD (
  CONSTRAINT DSS_WARRANTY_ORG_LINK_PK
  PRIMARY KEY
  (LNK_SEQ)
  USING INDEX DSS.DSS_WARRANTY_ORG_LINK_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_WARRANTY_ORG_LINK_U01
  UNIQUE (OPERATING_UNIT, WARRANTY_SEQ)
  USING INDEX DSS.DSS_WARRANTY_ORG_LINK_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_WARRANTY_ORG_LINK TO SELDATA;
