ALTER TABLE DSS.DSS_PRODUCT_ASSEMBLY_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_PRODUCT_ASSEMBLY_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_PRODUCT_ASSEMBLY_HEADER
(
  HEADERSEQ        NUMBER,
  OPERATING_UNIT   NUMBER                       NOT NULL,
  ORGANIZATION_ID  NUMBER                       NOT NULL,
  LOCATION_CODE    VARCHAR2(10 BYTE)            NOT NULL,
  ASSEMBLY_TYPE    VARCHAR2(10 BYTE)            NOT NULL,
  CREATE_BY        VARCHAR2(50 BYTE),
  CREATE_DATE      DATE                         DEFAULT SYSDATE,
  STATUS           CHAR(1 BYTE)                 DEFAULT 'A',
  POSTED           CHAR(1 BYTE)                 DEFAULT 'N',
  POST_DATE        DATE                         DEFAULT SYSDATE,
  MODIFY_DATE      DATE                         DEFAULT SYSDATE,
  MODIFY_BY        VARCHAR2(50 BYTE),
  REMARKS          VARCHAR2(2000 BYTE),
  REF_NUMBER       VARCHAR2(100 BYTE),
  ATTRIBUTE1       VARCHAR2(200 BYTE),
  ATTRIBUTE2       VARCHAR2(200 BYTE),
  ATTRIBUTE3       VARCHAR2(200 BYTE),
  ATTRIBUTE4       VARCHAR2(200 BYTE),
  ATTRIBUTE5       VARCHAR2(200 BYTE),
  ATTRIBUTE6       VARCHAR2(200 BYTE),
  ATTRIBUTE7       VARCHAR2(200 BYTE),
  ATTRIBUTE8       VARCHAR2(200 BYTE),
  ATTRIBUTE9       VARCHAR2(200 BYTE),
  ATTRIBUTE10      VARCHAR2(200 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_PRODUCT_ASSEMBLY_HEADER_PK ON DSS.DSS_PRODUCT_ASSEMBLY_HEADER
(HEADERSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_PRODUCT_ASSEMBLY_HEADER ADD (
  CONSTRAINT DSS_PRODUCT_ASSEMBLY_HEADER_PK
  PRIMARY KEY
  (HEADERSEQ)
  USING INDEX DSS.DSS_PRODUCT_ASSEMBLY_HEADER_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_PRODUCT_ASSEMBLY_HEADER TO SELDATA;
