ALTER TABLE DSS.DSS_ERROR_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ERROR_LOG CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ERROR_LOG
(
  LOGID            NUMBER,
  ERRORID          NUMBER,
  ERROR_LEVEL      VARCHAR2(200 BYTE),
  ERROR_ON         VARCHAR2(100 BYTE),
  ERROR_MESSAGE    VARCHAR2(1000 BYTE),
  ERROR_CODE       VARCHAR2(1000 BYTE),
  ORG_ID           NUMBER,
  ORGANIZATION_ID  NUMBER,
  LOCATION_CODE    VARCHAR2(20 BYTE),
  LINEID           NUMBER,
  PRODUCT_CODE     VARCHAR2(100 BYTE),
  REMARKS          VARCHAR2(1000 BYTE),
  CREATE_DATE      DATE,
  STATUS           CHAR(1 BYTE),
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ERROR_LOG_PK ON DSS.DSS_ERROR_LOG
(LOGID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_ERROR_LOG ADD (
  CONSTRAINT DSS_ERROR_LOG_PK
  PRIMARY KEY
  (LOGID)
  USING INDEX DSS.DSS_ERROR_LOG_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_ERROR_LOG TO SELDATA;
