DROP TABLE DSS.DSS_PRODUCTS_TEMP CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_PRODUCTS_TEMP
(
  LINEID                  NUMBER,
  OPERATING_UNIT          NUMBER,
  ORGANIZATION_ID         NUMBER                NOT NULL,
  INVENTORY_ITEM_ID       NUMBER                NOT NULL,
  PRODUCT_CODE            VARCHAR2(40 BYTE),
  DESCRIPTION             VARCHAR2(240 BYTE),
  PRODUCT_CLASSIFICATION  VARCHAR2(30 BYTE),
  ITEM_TYPE               VARCHAR2(30 BYTE),
  CATEGORY_ID             NUMBER,
  PURCHASE_TYPE           VARCHAR2(40 BYTE),
  BRAND_CODE              VARCHAR2(40 BYTE),
  MODEL_CODE              VARCHAR2(40 BYTE),
  CATEGORY_CODE           VARCHAR2(40 BYTE),
  SUB_CATEGORY_CODE       VARCHAR2(40 BYTE),
  SUB_SUB_CATEGORY_CODE   VARCHAR2(40 BYTE),
  COLOUR_CODE             VARCHAR2(240 BYTE),
  CAMERA                  VARCHAR2(240 BYTE),
  BLUETOOTH               VARCHAR2(240 BYTE),
  CONGIGNMENT             VARCHAR2(240 BYTE),
  ENABLED                 CHAR(1 BYTE)          NOT NULL,
  ACTIVE                  CHAR(1 BYTE),
  STOCK_ENABLED           CHAR(1 BYTE)          NOT NULL,
  OPTIMIZ_ENABLED         VARCHAR2(240 BYTE),
  LAST_UPDATE_DATE        DATE                  NOT NULL,
  CREATION_DATE           DATE                  NOT NULL,
  DWL_DATE                DATE,
  ATTRIBUTE1              VARCHAR2(100 BYTE),
  ATTRIBUTE2              VARCHAR2(100 BYTE),
  ATTRIBUTE3              VARCHAR2(100 BYTE),
  ATTRIBUTE4              VARCHAR2(100 BYTE),
  ATTRIBUTE5              VARCHAR2(100 BYTE),
  ATTRIBUTE6              VARCHAR2(100 BYTE),
  ATTRIBUTE7              VARCHAR2(100 BYTE),
  ATTRIBUTE8              VARCHAR2(100 BYTE),
  ATTRIBUTE9              VARCHAR2(100 BYTE),
  ATTRIBUTE10             VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON DSS.DSS_PRODUCTS_TEMP TO SELDATA;
