ALTER TABLE DSS.DSS_SERIALS_CHILD
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SERIALS_CHILD CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SERIALS_CHILD
(
  ROWSEQ        NUMBER                          NOT NULL,
  BRAND         VARCHAR2(100 BYTE),
  PARENTKEY     VARCHAR2(100 BYTE),
  ISPARENT      CHAR(1 BYTE)                    DEFAULT 'N',
  KEYID         NUMBER,
  SERIALKEY     VARCHAR2(100 BYTE),
  CREATED_DATE  DATE                            DEFAULT sysdate,
  DATA_SRC      VARCHAR2(100 BYTE)              DEFAULT 'SHIPMENT',
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DSS.DSS_SERIALS_CHILD_IX1 ON DSS.DSS_SERIALS_CHILD
(PARENTKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SERIAL_PK ON DSS.DSS_SERIALS_CHILD
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SERIAL_UNQ ON DSS.DSS_SERIALS_CHILD
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_SERIALS_CHILD_TRG
BEFORE INSERT
ON DSS.DSS_SERIALS_CHILD
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := SEQ_DSS_SERIALS_CHILD.nextval;
END DSS_SERIALS_CHILD_TRG;
/


ALTER TABLE DSS.DSS_SERIALS_CHILD ADD (
  CONSTRAINT DSS_SERIAL_PK
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.DSS_SERIAL_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_SERIAL_UNQ
  UNIQUE (SERIALKEY)
  USING INDEX DSS.DSS_SERIAL_UNQ
  ENABLE VALIDATE);

GRANT SELECT, UPDATE ON DSS.DSS_SERIALS_CHILD TO XXREPDSS;
