ALTER TABLE DSS.DSS_SALES_UPLD_HEAD
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SALES_UPLD_HEAD CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SALES_UPLD_HEAD
(
  HEADERSEQ          NUMBER,
  OPERATING_UNIT     NUMBER                     NOT NULL,
  ORGANIZATION_ID    NUMBER                     NOT NULL,
  LOCATION_CODE      VARCHAR2(10 BYTE)          NOT NULL,
  TRANSACTION_NO     VARCHAR2(50 BYTE)          NOT NULL,
  TRANSACTION_DATE   DATE                       NOT NULL,
  TRANSACTION_TYPE   VARCHAR2(50 BYTE)          NOT NULL,
  PARTY_CODE         VARCHAR2(40 BYTE),
  PARTY_NAME         VARCHAR2(40 BYTE),
  PARTY_SITE_NUMBER  VARCHAR2(50 BYTE),
  REMARKS            VARCHAR2(2000 BYTE),
  REF_NO1            VARCHAR2(100 BYTE),
  REF_NO2            VARCHAR2(100 BYTE),
  NET_AMOUNT         NUMBER(17,3),
  STATUS             CHAR(1 BYTE)               DEFAULT 'P',
  INTF_YN            CHAR(1 BYTE)               DEFAULT 'N',
  CREATE_DATE        DATE                       NOT NULL,
  CREATE_BY          VARCHAR2(100 BYTE),
  MODIFY_DATE        DATE                       NOT NULL,
  MODIFY_BY          VARCHAR2(100 BYTE),
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE),
  ATTRIBUTE8         VARCHAR2(100 BYTE),
  ATTRIBUTE9         VARCHAR2(100 BYTE),
  ATTRIBUTE10        VARCHAR2(100 BYTE),
  ATTRIBUTE11        VARCHAR2(100 BYTE),
  ATTRIBUTE12        VARCHAR2(100 BYTE),
  ATTRIBUTE13        VARCHAR2(100 BYTE),
  ATTRIBUTE14        VARCHAR2(100 BYTE),
  ATTRIBUTE15        VARCHAR2(100 BYTE),
  RESATTRIBUTE1      VARCHAR2(500 BYTE),
  RESATTRIBUTE2      VARCHAR2(500 BYTE),
  RESATTRIBUTE3      VARCHAR2(500 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DSS.DSS_SALES_UPLD_HEAD.ATTRIBUTE15 IS 'Number of lines in Excel Sheet realted to this Transaction';


CREATE UNIQUE INDEX DSS.DSS_SALES_UPLD_HEAD_PK ON DSS.DSS_SALES_UPLD_HEAD
(HEADERSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_SALES_UPLD_HEAD ADD (
  CONSTRAINT DSS_SALES_UPLD_HEAD_PK
  PRIMARY KEY
  (HEADERSEQ)
  USING INDEX DSS.DSS_SALES_UPLD_HEAD_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_SALES_UPLD_HEAD TO SELDATA;
