ALTER TABLE DSS.DSS_PRINT_TEMPLATE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_PRINT_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_PRINT_TEMPLATE
(
  TEMPID         NUMBER                         NOT NULL,
  DEPARTMENT     VARCHAR2(100 BYTE),
  TEMP_NAME      VARCHAR2(100 BYTE)             NOT NULL,
  DESCRIPTION    VARCHAR2(300 BYTE),
  TEMP_SCRIPT    VARCHAR2(4000 BYTE)            NOT NULL,
  SIZE_H         INTEGER,
  SIZE_W         INTEGER,
  UNITS          VARCHAR2(20 BYTE),
  HAS_IMAGE      CHAR(1 BYTE),
  SAMPLE_IMAGE   BLOB,
  IS_ACTIVE      CHAR(1 BYTE),
  STATUS         VARCHAR2(10 BYTE),
  CREATE_BY      VARCHAR2(50 BYTE)              NOT NULL,
  CREATE_DATE    DATE                           NOT NULL,
  MODIFIED_BY    VARCHAR2(50 BYTE),
  MODIFIED_DATE  DATE,
  ATTRIBUTE1     VARCHAR2(200 BYTE),
  ATTRIBUTE2     VARCHAR2(200 BYTE),
  ATTRIBUTE3     VARCHAR2(200 BYTE),
  ATTRIBUTE4     VARCHAR2(200 BYTE),
  ATTRIBUTE5     VARCHAR2(200 BYTE),
  ATTRIBUTE6     VARCHAR2(100 BYTE),
  ATTRIBUTE7     VARCHAR2(100 BYTE),
  ATTRIBUTE8     VARCHAR2(100 BYTE),
  ATTRIBUTE9     VARCHAR2(100 BYTE),
  ATTRIBUTE10    VARCHAR2(100 BYTE)
)
LOB (SAMPLE_IMAGE) STORE AS BASICFILE (
  TABLESPACE  AXM_TS_WMS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_PRINT_TEMPLATE_PK ON DSS.DSS_PRINT_TEMPLATE
(TEMPID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_PRINT_TEMPLATE ADD (
  CONSTRAINT DSS_PRINT_TEMPLATE_PK
  PRIMARY KEY
  (TEMPID)
  USING INDEX DSS.DSS_PRINT_TEMPLATE_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_PRINT_TEMPLATE TO SELDATA;
