ALTER TABLE DSS.DSS_SERVICE_BRANDS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SERVICE_BRANDS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SERVICE_BRANDS
(
  BRAND_SEQ         NUMBER,
  BRAND_CODE        VARCHAR2(30 BYTE),
  BRAND_DESC        VARCHAR2(100 BYTE),
  BRAND_SHORT_DESC  VARCHAR2(100 BYTE),
  ACTIVE            CHAR(1 BYTE),
  MAPPING_ID        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  ATTRIBUTE1        VARCHAR2(100 BYTE),
  ATTRIBUTE2        VARCHAR2(100 BYTE),
  ATTRIBUTE3        VARCHAR2(100 BYTE),
  ATTRIBUTE4        VARCHAR2(100 BYTE),
  ATTRIBUTE5        VARCHAR2(100 BYTE),
  ATTRIBUTE6        VARCHAR2(100 BYTE),
  ATTRIBUTE7        VARCHAR2(100 BYTE),
  ATTRIBUTE8        VARCHAR2(100 BYTE),
  ATTRIBUTE9        VARCHAR2(100 BYTE),
  ATTRIBUTE10       VARCHAR2(100 BYTE),
  ATTRIBUTE15       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_SERVICE_BRANDS_PK ON DSS.DSS_SERVICE_BRANDS
(BRAND_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SERVICE_BRANDS_U01 ON DSS.DSS_SERVICE_BRANDS
(BRAND_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_SERVICE_BRANDS ADD (
  CONSTRAINT DSS_SERVICE_BRANDS_PK
  PRIMARY KEY
  (BRAND_SEQ)
  USING INDEX DSS.DSS_SERVICE_BRANDS_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_SERVICE_BRANDS_U01
  UNIQUE (BRAND_CODE)
  USING INDEX DSS.DSS_SERVICE_BRANDS_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_SERVICE_BRANDS TO SELDATA;
