ALTER TABLE DSS.DSS_MANUAL_SCAN_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_MANUAL_SCAN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_MANUAL_SCAN_HEADER
(
  JOBID            NUMBER,
  APP_SOURCE       VARCHAR2(30 BYTE),
  LOC_TYPE         VARCHAR2(30 BYTE),
  OPERATING_UNIT   NUMBER,
  ORGANIZATION_ID  NUMBER,
  LOCATION_CODE    VARCHAR2(30 BYTE),
  LOC_REF_NO       NUMBER,
  LOC_REF_CODE     VARCHAR2(100 BYTE),
  TRANS_TYPE       VARCHAR2(30 BYTE),
  LINKED_TO_TYPE   VARCHAR2(30 BYTE),
  LINKED_TO_ID     NUMBER,
  LINKED_YN        CHAR(1 BYTE),
  WARRANTY_YN      CHAR(1 BYTE),
  ACTIVE_YN        CHAR(1 BYTE),
  STATUS           VARCHAR2(10 BYTE),
  EXPIRY_DATE      DATE,
  EXPIRY_AFTER     NUMBER,
  CREATE_DATE      DATE,
  CREATE_BY        VARCHAR2(30 BYTE),
  MODIFY_DATE      DATE,
  MODIFY_BY        VARCHAR2(30 BYTE),
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE),
  ATTRIBUTE6       VARCHAR2(100 BYTE),
  ATTRIBUTE7       VARCHAR2(100 BYTE),
  ATTRIBUTE8       VARCHAR2(100 BYTE),
  ATTRIBUTE9       VARCHAR2(100 BYTE),
  ATTRIBUTE10      VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION SCNHM_BFR_2015 VALUES LESS THAN (TO_DATE(' 2015-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SCNHM_2015 VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MHEADER_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_MANUAL_SCAN_HEADER_PK ON DSS.DSS_MANUAL_SCAN_HEADER
(JOBID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_MANUAL_SCAN_HEADER ADD (
  CONSTRAINT DSS_MANUAL_SCAN_HEADER_PK
  PRIMARY KEY
  (JOBID)
  USING INDEX DSS.DSS_MANUAL_SCAN_HEADER_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_MANUAL_SCAN_HEADER TO SELDATA;
