ALTER TABLE DSS.DSS_MANUAL_SCAN_LINES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_MANUAL_SCAN_LINES CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_MANUAL_SCAN_LINES
(
  JOBID                NUMBER,
  LINEID               NUMBER                   NOT NULL,
  TRANS_TYPE           VARCHAR2(30 BYTE),
  OPERATING_UNIT       NUMBER,
  ORGANIZATION_ID      NUMBER,
  LOCATION_CODE        VARCHAR2(30 BYTE),
  LOC_REF_CODE         VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID    NUMBER,
  PRODUCT_CODE         VARCHAR2(30 BYTE),
  PRODUCT_DESCRIPTION  VARCHAR2(100 BYTE),
  CAETGORY_ID          NUMBER,
  BRAND_SEQ            NUMBER,
  MODEL_SEQ            NUMBER,
  LINE_QTY             NUMBER,
  SCANNED_QTY          NUMBER,
  SCAN_YN              CHAR(1 BYTE),
  SYNC_YN              CHAR(1 BYTE),
  WARRANTY_YN          CHAR(1 BYTE),
  WARRANTY_SEQ         NUMBER,
  WARRANTY_CODE        VARCHAR2(30 BYTE),
  EDITABLE_YN          CHAR(1 BYTE),
  ARCHIVED_YN          CHAR(1 BYTE),
  ACTIVE_YN            CHAR(1 BYTE),
  STATUS_YN            CHAR(1 BYTE),
  HAS_SERIALS          CHAR(1 BYTE),
  BARCODES             VARCHAR2(100 BYTE),
  EXPIRY_DATE          DATE,
  EXPIRY_DAYS          NUMBER,
  CREATE_DATE          DATE,
  CREATE_BY            VARCHAR2(30 BYTE),
  MODIFY_DATE          DATE,
  MODIFY_BY            VARCHAR2(30 BYTE),
  ATTRIBUTE1           VARCHAR2(100 BYTE),
  ATTRIBUTE2           VARCHAR2(100 BYTE),
  ATTRIBUTE3           VARCHAR2(100 BYTE),
  ATTRIBUTE4           VARCHAR2(100 BYTE),
  ATTRIBUTE5           VARCHAR2(100 BYTE),
  ATTRIBUTE6           VARCHAR2(100 BYTE),
  ATTRIBUTE7           VARCHAR2(100 BYTE),
  ATTRIBUTE8           VARCHAR2(100 BYTE),
  ATTRIBUTE9           VARCHAR2(100 BYTE),
  ATTRIBUTE10          VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION MLINES_2012 VALUES LESS THAN (TO_DATE(' 2013-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2013 VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2014 VALUES LESS THAN (TO_DATE(' 2015-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2015_Q1 VALUES LESS THAN (TO_DATE(' 2015-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2015_Q2 VALUES LESS THAN (TO_DATE(' 2015-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2015_Q3 VALUES LESS THAN (TO_DATE(' 2015-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2015_Q4 VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2016_Q1 VALUES LESS THAN (TO_DATE(' 2016-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2016_Q2 VALUES LESS THAN (TO_DATE(' 2016-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2016_Q3 VALUES LESS THAN (TO_DATE(' 2016-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_2016_Q4 VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION MLINES_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_MANUAL_SCAN_LINES_PK ON DSS.DSS_MANUAL_SCAN_LINES
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_MANUAL_SCAN_LINES ADD (
  CONSTRAINT DSS_MANUAL_SCAN_LINES_PK
  PRIMARY KEY
  (LINEID)
  USING INDEX DSS.DSS_MANUAL_SCAN_LINES_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_MANUAL_SCAN_LINES TO SELDATA;
