ALTER TABLE DSS.DSS_DISPATCH_TRACKING
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_DISPATCH_TRACKING CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_DISPATCH_TRACKING
(
  TRACK_ID             NUMBER,
  SRC_ORGID            NUMBER,
  SRC_ORGANIZATIONID   NUMBER,
  SRC_LOCATION         VARCHAR2(30 BYTE),
  DEST_ORGID           NUMBER,
  DEST_ORGANIZATIONID  NUMBER,
  DEST_LOCATION        VARCHAR2(30 BYTE),
  ORDER_TYPE           VARCHAR2(30 BYTE),
  ORDER_NUMBER         VARCHAR2(30 BYTE),
  PICK_ID              VARCHAR2(50 BYTE),
  ORDER_DATE           DATE,
  VEHICLE_NUMBER       VARCHAR2(50 BYTE),
  CHECK_IN             DATE,
  CHECK_OUT            DATE,
  SALESMAN_ID          NUMBER,
  SALESMAN_NAME        VARCHAR2(100 BYTE),
  SALESMAN_LOCATION    VARCHAR2(50 BYTE),
  SECURITY_ID          VARCHAR2(50 BYTE),
  SECURITY_NAME        VARCHAR2(100 BYTE),
  SRC_LOCATION_NAME    VARCHAR2(100 BYTE),
  DEST_LOCATION_NAME   VARCHAR2(100 BYTE),
  REMARKS              VARCHAR2(300 BYTE),
  STATUS               CHAR(1 BYTE),
  CREATED_BY           VARCHAR2(30 BYTE),
  CREATE_DATE          DATE,
  ATTRIBUTE1           VARCHAR2(100 BYTE),
  ATTRIBUTE2           VARCHAR2(100 BYTE),
  ATTRIBUTE3           VARCHAR2(100 BYTE),
  ATTRIBUTE4           VARCHAR2(100 BYTE),
  ATTRIBUTE5           VARCHAR2(100 BYTE),
  ATTRIBUTE6           VARCHAR2(100 BYTE),
  ATTRIBUTE7           VARCHAR2(100 BYTE),
  ATTRIBUTE8           VARCHAR2(100 BYTE),
  ATTRIBUTE9           VARCHAR2(100 BYTE),
  ATTRIBUTE10          VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_DISPATCH_TRACKING_PK ON DSS.DSS_DISPATCH_TRACKING
(TRACK_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_DISPATCH_TRACKING ADD (
  CONSTRAINT DSS_DISPATCH_TRACKING_PK
  PRIMARY KEY
  (TRACK_ID)
  USING INDEX DSS.DSS_DISPATCH_TRACKING_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_DISPATCH_TRACKING TO SELDATA;
