ALTER TABLE DSS.DSS_SERIALS_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SERIALS_MASTER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SERIALS_MASTER
(
  ROWSEQ         NUMBER                         NOT NULL,
  SERIALKEY      VARCHAR2(100 BYTE)             NOT NULL,
  PARENTKEY      VARCHAR2(100 BYTE),
  PRODUCT_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  ISPARENT       CHAR(1 BYTE)                   DEFAULT 'N',
  HASCHILD       CHAR(1 BYTE)                   DEFAULT 'N',
  LAST_SCANDATE  DATE,
  CREATE_DATE    DATE                           DEFAULT SYSDATE,
  UPDATE_CNT     NUMBER,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX DSS.DSS_SERIALS_MASTER_IX1 ON DSS.DSS_SERIALS_MASTER
(PARENTKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.PK_DSS_ROWSEQ ON DSS.DSS_SERIALS_MASTER
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.UQ_DSS_SERIALS_MASTER ON DSS.DSS_SERIALS_MASTER
(SERIALKEY, PRODUCT_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_SERIALS_MASTER_TRG
   BEFORE INSERT
   ON DSS.DSS_SERIALS_MASTER
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column ROWSEQ
   :new.ROWSEQ := SEQ_DSS_SERIALS_MASTER.NEXTVAL;
END DSS_SERIALS_MASTER_TRG;
/


ALTER TABLE DSS.DSS_SERIALS_MASTER ADD (
  CONSTRAINT PK_DSS_ROWSEQ
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.PK_DSS_ROWSEQ
  ENABLE VALIDATE,
  CONSTRAINT UQ_DSS_SERIALS_MASTER
  UNIQUE (SERIALKEY, PRODUCT_CODE)
  USING INDEX DSS.UQ_DSS_SERIALS_MASTER
  ENABLE VALIDATE);

GRANT SELECT, UPDATE ON DSS.DSS_SERIALS_MASTER TO XXREPDSS;
