ALTER TABLE DSS.DSS_API_SERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_API_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_API_SERIALS
(
  SCANID                 NUMBER,
  BATCHID                NUMBER,
  LINEID                 NUMBER,
  SEQINDEX               NUMBER,
  COLUMNINDEX            NUMBER,
  CONFIGID               NUMBER,
  CONFIGTYPE             VARCHAR2(100 BYTE),
  SCANTYPE               VARCHAR2(100 BYTE),
  SCAN_SOURCE            VARCHAR2(100 BYTE),
  SRC_TYPE               VARCHAR2(30 BYTE),
  SRC_OPERATING_UNIT     NUMBER,
  SRC_ORGANIZATION_ID    NUMBER,
  SRC_LOCATION_CODE      VARCHAR2(30 BYTE),
  DEST_TYPE              VARCHAR2(30 BYTE),
  DEST_OPERATING_UNIT    NUMBER,
  DEST_ORGANIZATION_ID   NUMBER,
  DEST_LOCATION_CODE     VARCHAR2(30 BYTE),
  ORDER_TYPE             VARCHAR2(30 BYTE),
  ORDER_NUMBER           VARCHAR2(100 BYTE),
  ORDER_REF_NO1          VARCHAR2(100 BYTE),
  ORDER_REF_NO2          VARCHAR2(100 BYTE),
  ORDER_DATE             DATE,
  SERIALKEY              VARCHAR2(100 BYTE),
  SERIALKEY_REF1         VARCHAR2(100 BYTE),
  SERIALKEY_REF2         VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID      NUMBER,
  PRODUCT_CODE           VARCHAR2(100 BYTE),
  PRODUCT_DESC           VARCHAR2(200 BYTE),
  BRAND                  VARCHAR2(30 BYTE),
  CATEGORY_ID            NUMBER,
  CATEGORY_CODE          VARCHAR2(30 BYTE),
  CATEGORY_DESC          VARCHAR2(100 BYTE),
  SUB_CATEGORY_CODE      VARCHAR2(30 BYTE),
  SUB_CATEGORY_DESC      VARCHAR2(100 BYTE),
  SUB_SUB_CATEGORY_CODE  VARCHAR2(30 BYTE),
  SUB_SUB_CATEGORY_DESC  VARCHAR2(100 BYTE),
  WARRANTY_YN            CHAR(1 BYTE),
  WARRANTY_SEQ           NUMBER,
  WARRANTY_CODE          VARCHAR2(50 BYTE),
  WARRANTY_STARTDATE     DATE,
  WARRANTY_ENDDATE       DATE,
  ACTIVE_YN              CHAR(1 BYTE),
  STATUS                 VARCHAR2(50 BYTE),
  INF_YN                 CHAR(1 BYTE),
  INF_DATE               DATE,
  REMARKS                VARCHAR2(300 BYTE),
  CREATE_BY              VARCHAR2(50 BYTE),
  CREATE_DATE            DATE,
  MODIFY_BY              VARCHAR2(50 BYTE),
  MODIFY_DATE            DATE,
  ALLOW_EDIT             CHAR(1 BYTE),
  ALLOW_INF              CHAR(1 BYTE),
  ATTRIBUTE1             VARCHAR2(100 BYTE),
  ATTRIBUTE2             VARCHAR2(100 BYTE),
  ATTRIBUTE3             VARCHAR2(100 BYTE),
  ATTRIBUTE4             VARCHAR2(100 BYTE),
  ATTRIBUTE5             VARCHAR2(100 BYTE),
  ATTRIBUTE6             VARCHAR2(100 BYTE),
  ATTRIBUTE7             VARCHAR2(100 BYTE),
  ATTRIBUTE8             VARCHAR2(100 BYTE),
  ATTRIBUTE9             VARCHAR2(100 BYTE),
  ATTRIBUTE10            VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION SERIALS_2016_Q4 VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2017_Q1 VALUES LESS THAN (TO_DATE(' 2017-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2017_Q2 VALUES LESS THAN (TO_DATE(' 2017-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2017_Q3 VALUES LESS THAN (TO_DATE(' 2017-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2017_Q4 VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q1 VALUES LESS THAN (TO_DATE(' 2018-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q2 VALUES LESS THAN (TO_DATE(' 2018-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q3 VALUES LESS THAN (TO_DATE(' 2018-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q4 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q1 VALUES LESS THAN (TO_DATE(' 2019-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q2 VALUES LESS THAN (TO_DATE(' 2019-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q3 VALUES LESS THAN (TO_DATE(' 2019-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q4 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2020_Q1 VALUES LESS THAN (TO_DATE(' 2020-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2020_Q2 VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2020_Q3 VALUES LESS THAN (TO_DATE(' 2020-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2020_Q4 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_API_SERIALS_PK ON DSS.DSS_API_SERIALS
(SCANID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_API_SERIALS_U01 ON DSS.DSS_API_SERIALS
(COLUMNINDEX, SEQINDEX, LINEID, BATCHID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_API_SERIALS_U02 ON DSS.DSS_API_SERIALS
(SERIALKEY, BATCHID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_API_SERIALS ADD (
  CONSTRAINT DSS_API_SERIALS_PK
  PRIMARY KEY
  (SCANID)
  USING INDEX DSS.DSS_API_SERIALS_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_API_SERIALS_U01
  UNIQUE (COLUMNINDEX, SEQINDEX, LINEID, BATCHID)
  USING INDEX DSS.DSS_API_SERIALS_U01
  ENABLE VALIDATE,
  CONSTRAINT DSS_API_SERIALS_U02
  UNIQUE (SERIALKEY, BATCHID)
  USING INDEX DSS.DSS_API_SERIALS_U02
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_API_SERIALS TO SELDATA;
