ALTER TABLE DSS.DSS_FRAGMENT_HEADER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_FRAGMENT_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_FRAGMENT_HEADER
(
  HEADERSEQ        NUMBER                       NOT NULL,
  OPERATING_UNIT   NUMBER                       NOT NULL,
  ORGANIZATION_ID  NUMBER                       NOT NULL,
  LOCATION_CODE    VARCHAR2(20 BYTE),
  FRAGMENT_TYPE    VARCHAR2(50 BYTE),
  STATUS           VARCHAR2(20 BYTE),
  POSTED           CHAR(1 BYTE),
  POST_DATE        DATE,
  REMARKS          VARCHAR2(300 BYTE),
  REFERENCE_1      VARCHAR2(100 BYTE),
  REFERENCE_2      VARCHAR2(100 BYTE),
  CREATE_BY        VARCHAR2(50 BYTE),
  CREATE_DATE      DATE,
  MODIFY_BY        VARCHAR2(50 BYTE),
  MODIFY_DATE      DATE,
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE),
  ATTRIBUTE6       VARCHAR2(100 BYTE),
  ATTRIBUTE7       VARCHAR2(100 BYTE),
  ATTRIBUTE8       VARCHAR2(100 BYTE),
  ATTRIBUTE9       VARCHAR2(100 BYTE),
  ATTRIBUTE10      VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_FRAGMENT_HEADER_PK ON DSS.DSS_FRAGMENT_HEADER
(HEADERSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_FRAGMENT_HEADER ADD (
  CONSTRAINT DSS_FRAGMENT_HEADER_PK
  PRIMARY KEY
  (HEADERSEQ)
  USING INDEX DSS.DSS_FRAGMENT_HEADER_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_FRAGMENT_HEADER TO SELDATA;
