ALTER TABLE DSS.DSS_INTERFACE_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_INTERFACE_LOG CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_INTERFACE_LOG
(
  LOGID             NUMBER,
  INTERFACEID       NUMBER,
  TRANSACTION_TYPE  VARCHAR2(100 BYTE),
  RUN_DATE          DATE,
  ROW_COUNT         NUMBER,
  STATUS            CHAR(1 BYTE),
  ERROR_MESSAGE     VARCHAR2(300 BYTE),
  STARTDATE         DATE,
  ENDATE            DATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_INTERFACE_LOG_PK ON DSS.DSS_INTERFACE_LOG
(LOGID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_INTERFACE_LOG_TRG
BEFORE INSERT
ON DSS.DSS_INTERFACE_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LOGID
  :new.LOGID := SEQ_DSS_INTERFACE_LOG.nextval;
END DSS_INTERFACE_LOG_TRG;
/


ALTER TABLE DSS.DSS_INTERFACE_LOG ADD (
  CONSTRAINT DSS_INTERFACE_LOG_PK
  PRIMARY KEY
  (LOGID)
  USING INDEX DSS.DSS_INTERFACE_LOG_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_INTERFACE_LOG TO SELDATA;

GRANT SELECT, UPDATE ON DSS.DSS_INTERFACE_LOG TO XXREPDSS;
