ALTER TABLE DSS.DSS_REPORTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_REPORTS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_REPORTS
(
  REPT_ID         NUMBER                        NOT NULL,
  PARENT_ID       NUMBER                        NOT NULL,
  REPT_NAME       VARCHAR2(100 BYTE)            NOT NULL,
  REPT_PACKAGE    VARCHAR2(50 BYTE)             NOT NULL,
  REPT_PROCEDURE  VARCHAR2(50 BYTE)             NOT NULL,
  IS_REPORT       CHAR(1 BYTE)                  NOT NULL,
  IS_ACTIVE       CHAR(1 BYTE)                  NOT NULL,
  IS_PAGING       CHAR(1 BYTE),
  IS_DEFAULT      CHAR(1 BYTE)                  NOT NULL,
  CREATE_BY       VARCHAR2(50 BYTE)             NOT NULL,
  CREATE_DATE     DATE                          NOT NULL,
  MODIFY_BY       VARCHAR2(50 BYTE),
  MODIFY_DATE     DATE,
  ATTRIBUTE1      VARCHAR2(100 BYTE),
  ATTRIBUTE2      VARCHAR2(100 BYTE),
  ATTRIBUTE3      VARCHAR2(100 BYTE),
  ATTRIBUTE4      VARCHAR2(100 BYTE),
  ATTRIBUTE5      VARCHAR2(100 BYTE),
  ATTRIBUTE6      VARCHAR2(100 BYTE),
  ATTRIBUTE7      VARCHAR2(100 BYTE),
  ATTRIBUTE8      VARCHAR2(100 BYTE),
  ATTRIBUTE9      VARCHAR2(100 BYTE),
  ATTRIBUTE10     VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_REPORTS_PK ON DSS.DSS_REPORTS
(REPT_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_REPORTS ADD (
  CONSTRAINT DSS_REPORTS_PK
  PRIMARY KEY
  (REPT_ID)
  USING INDEX DSS.DSS_REPORTS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_REPORTS TO SELDATA;
