ALTER TABLE DSS.DSS_BRAND_MAPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_BRAND_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_BRAND_MAPPING
(
  ITEM_BRD_SEQ      NUMBER,
  ITEM_BRD_CODE     VARCHAR2(30 BYTE),
  ITEM_BRD_NAME     VARCHAR2(100 BYTE),
  ITEM_BRD_DESC     VARCHAR2(500 BYTE),
  ITEM_SHRT_DESC    VARCHAR2(100 BYTE),
  ITEM_BRD_ACTIVE   CHAR(1 BYTE),
  CREATION_DATE     DATE,
  LAST_UPDATE_DATE  DATE,
  ATTRIBUTE1        VARCHAR2(100 BYTE),
  ATTRIBUTE2        VARCHAR2(100 BYTE),
  ATTRIBUTE3        VARCHAR2(100 BYTE),
  ATTRIBUTE4        VARCHAR2(100 BYTE),
  ATTRIBUTE5        VARCHAR2(100 BYTE),
  ATTRIBUTE6        VARCHAR2(100 BYTE),
  ATTRIBUTE7        VARCHAR2(100 BYTE),
  ATTRIBUTE8        VARCHAR2(100 BYTE),
  ATTRIBUTE9        VARCHAR2(100 BYTE),
  ATTRIBUTE10       VARCHAR2(100 BYTE),
  ATTRIBUTE15       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_BRAND_MAPPING_PK ON DSS.DSS_BRAND_MAPPING
(ITEM_BRD_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_BRAND_MAPPING_U01 ON DSS.DSS_BRAND_MAPPING
(ITEM_BRD_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_BRAND_MAPPING ADD (
  CONSTRAINT DSS_BRAND_MAPPING_PK
  PRIMARY KEY
  (ITEM_BRD_SEQ)
  USING INDEX DSS.DSS_BRAND_MAPPING_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_BRAND_MAPPING_U01
  UNIQUE (ITEM_BRD_CODE)
  USING INDEX DSS.DSS_BRAND_MAPPING_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_BRAND_MAPPING TO SELDATA;
