ALTER TABLE DSS.DSS_DU_UPLD_SRC
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_DU_UPLD_SRC CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_DU_UPLD_SRC
(
  ROW_SEQ         NUMBER,
  OPERATING_UNIT  NVARCHAR2(10),
  ORG_ID          NVARCHAR2(10),
  PRODUCT_CODE    NVARCHAR2(150),
  BATCH_ID        NVARCHAR2(50),
  ICC_ID          NUMBER,
  MSISDN          NUMBER,
  BOX_ID          NVARCHAR2(10),
  PALLET_ID       NVARCHAR2(15),
  EXPIRY_YN       NVARCHAR2(10),
  CREATED_DATE    DATE,
  CREATED_BY      NVARCHAR2(50),
  ATTRIBUTE1      NVARCHAR2(10),
  ATTRIBUTE2      NVARCHAR2(50),
  ATTRIBUTE3      NVARCHAR2(100),
  ATTRIBUTE4      NVARCHAR2(100),
  ATTRIBUTE5      NVARCHAR2(100),
  ATTRIBUTE6      NVARCHAR2(100)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_DU_UPLD_SRC_PK ON DSS.DSS_DU_UPLD_SRC
(ROW_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_DU_UPLD_SRC ADD (
  CONSTRAINT DSS_DU_UPLD_SRC_PK
  PRIMARY KEY
  (ROW_SEQ)
  USING INDEX DSS.DSS_DU_UPLD_SRC_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_DU_UPLD_SRC TO SELDATA;
