ALTER TABLE DSS.DSS_USER_NOTIFICATIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_USER_NOTIFICATIONS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_USER_NOTIFICATIONS
(
  ID           NUMBER,
  NOTIFY_TYPE  VARCHAR2(20 BYTE),
  NOTIFY_FOR   VARCHAR2(100 BYTE),
  RECIPIENT    VARCHAR2(100 BYTE),
  ACTIVE       VARCHAR2(10 BYTE),
  CREATE_BY    VARCHAR2(30 BYTE),
  CREATE_DATE  DATE,
  ATTRIBUTE1   VARCHAR2(100 BYTE),
  ATTRIBUTE2   VARCHAR2(100 BYTE),
  ATTRIBUTE3   VARCHAR2(100 BYTE),
  ATTRIBUTE4   VARCHAR2(100 BYTE),
  ATTRIBUTE5   VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DSS.DSS_USER_NOTIFICATIONS.NOTIFY_TYPE IS 'E - EMAIL, S- SMS';

COMMENT ON COLUMN DSS.DSS_USER_NOTIFICATIONS.NOTIFY_FOR IS 'ALL - FOR ALL NOTIFICATION, OR SPECIFIC NAME';

COMMENT ON COLUMN DSS.DSS_USER_NOTIFICATIONS.ATTRIBUTE1 IS 'USER NAME';


CREATE UNIQUE INDEX DSS.DSS_USER_NOTIFICATIONS_PK ON DSS.DSS_USER_NOTIFICATIONS
(ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_USER_NOTIFICATIONS_U01 ON DSS.DSS_USER_NOTIFICATIONS
(NOTIFY_TYPE, NOTIFY_FOR, RECIPIENT)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_USER_NOTIFICATIONS ADD (
  CONSTRAINT DSS_USER_NOTIFICATIONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX DSS.DSS_USER_NOTIFICATIONS_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_USER_NOTIFICATIONS_U01
  UNIQUE (NOTIFY_TYPE, NOTIFY_FOR, RECIPIENT)
  USING INDEX DSS.DSS_USER_NOTIFICATIONS_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_USER_NOTIFICATIONS TO SELDATA;
