ALTER TABLE DSS.DSS_SERVICE_WARRANTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_SERVICE_WARRANTY CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SERVICE_WARRANTY
(
  WARRANTY_SEQ         NUMBER,
  BRAND_SEQ            NUMBER,
  WARRANTY_CODE        VARCHAR2(100 BYTE),
  WARRANTY_DESC        VARCHAR2(500 BYTE),
  WARRANTY_SHORT_DESC  VARCHAR2(250 BYTE),
  WARRANTY_CATG_FLAG   CHAR(1 BYTE),
  WARRANTY_ACTIVE      CHAR(1 BYTE),
  WARRANTY_TYPE        VARCHAR2(30 BYTE),
  NO_YEARS             NUMBER,
  NO_MONTHS            NUMBER,
  NO_DAYS              NUMBER,
  REF_WARRANTY_CODE    NUMBER,
  OFFLINE_ENABLED      CHAR(1 BYTE),
  WMS_ENABLED          CHAR(1 BYTE),
  CREATION_DATE        DATE,
  LAST_UPDATE_DATE     DATE,
  ATTRIBUTE1           VARCHAR2(100 BYTE),
  ATTRIBUTE2           VARCHAR2(100 BYTE),
  ATTRIBUTE3           VARCHAR2(100 BYTE),
  ATTRIBUTE4           VARCHAR2(100 BYTE),
  ATTRIBUTE5           VARCHAR2(100 BYTE),
  ATTRIBUTE6           VARCHAR2(100 BYTE),
  ATTRIBUTE7           VARCHAR2(100 BYTE),
  ATTRIBUTE8           VARCHAR2(100 BYTE),
  ATTRIBUTE9           VARCHAR2(100 BYTE),
  ATTRIBUTE10          VARCHAR2(100 BYTE),
  ATTRIBUTE15          VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_SERVICE_WARRANTY_PK ON DSS.DSS_SERVICE_WARRANTY
(WARRANTY_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SERVICE_WARRANTY_U01 ON DSS.DSS_SERVICE_WARRANTY
(WARRANTY_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_SERVICE_WARRANTY ADD (
  CONSTRAINT DSS_SERVICE_WARRANTY_PK
  PRIMARY KEY
  (WARRANTY_SEQ)
  USING INDEX DSS.DSS_SERVICE_WARRANTY_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_SERVICE_WARRANTY_U01
  UNIQUE (WARRANTY_CODE)
  USING INDEX DSS.DSS_SERVICE_WARRANTY_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_SERVICE_WARRANTY TO SELDATA;
