ALTER TABLE DSS.DSS_MANIFEST_PRINT_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_MANIFEST_PRINT_INFO CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_MANIFEST_PRINT_INFO
(
  SEQNO             NUMBER,
  OPERATING_UNIT    NUMBER,
  ORGANIZATION_ID   NUMBER,
  LOCATION_CODE     VARCHAR2(20 BYTE),
  ORDER_TYPE        VARCHAR2(20 BYTE),
  ORDER_NUMBER      VARCHAR2(30 BYTE),
  QUANTITY          NUMBER,
  ROUTE_NO          NUMBER,
  BAG_COUNT         NUMBER,
  BAG_NUMBER        NUMBER,
  BAG_REFERENCE_NO  VARCHAR2(30 BYTE),
  SEAL_NUMBER       VARCHAR2(30 BYTE),
  SEAL_NUMBER_REF1  VARCHAR2(30 BYTE),
  SEAL_NUMBER_REF2  VARCHAR2(30 BYTE),
  CREATE_BY         VARCHAR2(30 BYTE),
  CREATE_DATE       DATE,
  ATTRIBUTE1        VARCHAR2(50 BYTE),
  ATTRIBUTE2        VARCHAR2(50 BYTE),
  ATTRIBUTE3        VARCHAR2(50 BYTE),
  ATTRIBUTE4        VARCHAR2(50 BYTE),
  ATTRIBUTE5        VARCHAR2(50 BYTE),
  ATTRIBUTE6        VARCHAR2(50 BYTE),
  ATTRIBUTE7        VARCHAR2(50 BYTE),
  ATTRIBUTE8        VARCHAR2(50 BYTE),
  ATTRIBUTE9        VARCHAR2(50 BYTE),
  ATTRIBUTE10       VARCHAR2(50 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION PART_2016 VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2017 VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2018 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2019 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2020 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2021 VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2022 VALUES LESS THAN (TO_DATE(' 2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_2023 VALUES LESS THAN (TO_DATE(' 2024-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION PART_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE INDEX DSS.DSS_MANIFEST_PRINT_INFO_IX23 ON DSS.DSS_MANIFEST_PRINT_INFO
(SEAL_NUMBER)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_MANIFEST_PRINT_INFO_PK ON DSS.DSS_MANIFEST_PRINT_INFO
(SEQNO)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_MANIFEST_PRINT_INFO ADD (
  CONSTRAINT DSS_MANIFEST_PRINT_INFO_PK
  PRIMARY KEY
  (SEQNO)
  USING INDEX DSS.DSS_MANIFEST_PRINT_INFO_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_MANIFEST_PRINT_INFO TO SELDATA;
