ALTER TABLE DSS.DSS_PRODUCTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_PRODUCTS
(
  LINEID                  NUMBER,
  OPERATING_UNIT          NUMBER,
  ORGANIZATION_ID         NUMBER                NOT NULL,
  INVENTORY_ITEM_ID       NUMBER                NOT NULL,
  PRODUCT_CODE            VARCHAR2(40 BYTE),
  DESCRIPTION             VARCHAR2(240 BYTE),
  PRODUCT_CLASSIFICATION  VARCHAR2(30 BYTE),
  ITEM_TYPE               VARCHAR2(30 BYTE),
  CATEGORY_ID             NUMBER,
  PURCHASE_TYPE           VARCHAR2(40 BYTE),
  BRAND_CODE              VARCHAR2(40 BYTE),
  MODEL_CODE              VARCHAR2(40 BYTE),
  CATEGORY_CODE           VARCHAR2(40 BYTE),
  SUB_CATEGORY_CODE       VARCHAR2(40 BYTE),
  SUB_SUB_CATEGORY_CODE   VARCHAR2(40 BYTE),
  COLOUR_CODE             VARCHAR2(240 BYTE),
  CAMERA                  VARCHAR2(240 BYTE),
  BLUETOOTH               VARCHAR2(240 BYTE),
  CONGIGNMENT             VARCHAR2(240 BYTE),
  ENABLED                 CHAR(1 BYTE)          NOT NULL,
  ACTIVE                  CHAR(1 BYTE),
  STOCK_ENABLED           CHAR(1 BYTE)          NOT NULL,
  OPTIMIZ_ENABLED         VARCHAR2(240 BYTE),
  LAST_UPDATE_DATE        DATE                  NOT NULL,
  CREATION_DATE           DATE                  NOT NULL,
  DWL_DATE                DATE                  DEFAULT SYSDATE,
  ATTRIBUTE1              VARCHAR2(100 BYTE),
  ATTRIBUTE2              VARCHAR2(100 BYTE),
  ATTRIBUTE3              VARCHAR2(100 BYTE),
  ATTRIBUTE4              VARCHAR2(100 BYTE),
  ATTRIBUTE5              VARCHAR2(100 BYTE),
  ATTRIBUTE6              VARCHAR2(100 BYTE),
  ATTRIBUTE7              VARCHAR2(100 BYTE),
  ATTRIBUTE8              VARCHAR2(100 BYTE),
  ATTRIBUTE9              VARCHAR2(100 BYTE),
  ATTRIBUTE10             VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DSS.DSS_PRODUCTS.ATTRIBUTE1 IS 'Base brand';


CREATE INDEX DSS.DSS_PRODUCTS_IX3 ON DSS.DSS_PRODUCTS
(OPERATING_UNIT, ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.DSS_PRODUCTS_IX4 ON DSS.DSS_PRODUCTS
(CATEGORY_ID, MODEL_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.DSS_PRODUCTS_IXCP ON DSS.DSS_PRODUCTS
(CATEGORY_CODE, PRODUCT_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_PRODUCTS_PK ON DSS.DSS_PRODUCTS
(INVENTORY_ITEM_ID, ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_PRODUCTS_U01 ON DSS.DSS_PRODUCTS
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.DSS_PRODUCTS_X2 ON DSS.DSS_PRODUCTS
(ORGANIZATION_ID, INVENTORY_ITEM_ID, PRODUCT_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_PRODUCTS_TRG
BEFORE INSERT
ON DSS.DSS_PRODUCTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := SEQ_DSS_PRODUCTS_ID.nextval;
END DSS_PRODUCTS_TRG;
/


ALTER TABLE DSS.DSS_PRODUCTS ADD (
  CONSTRAINT DSS_PRODUCTS_PK
  PRIMARY KEY
  (INVENTORY_ITEM_ID, ORGANIZATION_ID)
  USING INDEX DSS.DSS_PRODUCTS_PK
  ENABLE VALIDATE,
  CONSTRAINT DSS_PRODUCTS_U01
  UNIQUE (LINEID)
  USING INDEX DSS.DSS_PRODUCTS_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_PRODUCTS TO CFROTEST;

GRANT SELECT ON DSS.DSS_PRODUCTS TO SELDATA;
