ALTER TABLE DSS.DSS_ORDER_SCAN_PERFORMANCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ORDER_SCAN_PERFORMANCE CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ORDER_SCAN_PERFORMANCE
(
  SEQNO         NUMBER,
  JOBID         NUMBER,
  ORDER_TYPE    VARCHAR2(20 BYTE),
  ORDER_NUMBER  VARCHAR2(100 BYTE),
  ORDER_DATE    DATE,
  LINES_COUNT   NUMBER,
  TOTAL_QTY     NUMBER,
  SCANNED_QTY   NUMBER,
  START_TIME    DATE,
  END_TIME      DATE,
  DURATION      NUMBER,
  CREATE_BY     VARCHAR2(30 BYTE),
  STATUS        VARCHAR2(30 BYTE),
  REMARKS       VARCHAR2(100 BYTE),
  ATTRIBUTE1    VARCHAR2(100 BYTE),
  ATTRIBUTE2    VARCHAR2(100 BYTE),
  ATTRIBUTE3    VARCHAR2(100 BYTE),
  ATTRIBUTE4    VARCHAR2(100 BYTE),
  ATTRIBUTE5    VARCHAR2(100 BYTE),
  ATTRIBUTE6    VARCHAR2(100 BYTE),
  ATTRIBUTE7    VARCHAR2(100 BYTE),
  ATTRIBUTE8    VARCHAR2(100 BYTE),
  ATTRIBUTE9    VARCHAR2(100 BYTE),
  ATTRIBUTE10   VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
PARTITION BY RANGE (ORDER_DATE)
(  
  PARTITION DSCNP_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ORDER_SCAN_PERFORMANCE_PK ON DSS.DSS_ORDER_SCAN_PERFORMANCE
(SEQNO)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_ORDER_SCAN_PERFORMANCE ADD (
  CONSTRAINT DSS_ORDER_SCAN_PERFORMANCE_PK
  PRIMARY KEY
  (SEQNO)
  USING INDEX DSS.DSS_ORDER_SCAN_PERFORMANCE_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_ORDER_SCAN_PERFORMANCE TO SELDATA;
