DROP TABLE DSS.DSS_FILE_SERIALS_BK04042019 CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_FILE_SERIALS_BK04042019
(
  ROWSEQ             NUMBER                     NOT NULL,
  FILE_SEQ           NUMBER,
  COUNTRY_CODE       VARCHAR2(50 BYTE)          NOT NULL,
  UPL_SEQ            NUMBER,
  PARENTKEY          VARCHAR2(50 BYTE),
  ISPARENT           CHAR(1 BYTE),
  KEYID              NUMBER,
  SERIALKEY          VARCHAR2(50 BYTE),
  BRAND              VARCHAR2(100 BYTE),
  PART_CODE1         VARCHAR2(50 BYTE),
  PART_CODE2         VARCHAR2(50 BYTE),
  EAN_CODE1          VARCHAR2(50 BYTE),
  EAN_CODE2          VARCHAR2(100 BYTE),
  MODEL_CODE1        VARCHAR2(100 BYTE),
  MODEL_CODE2        VARCHAR2(100 BYTE),
  INVOICE_NO         VARCHAR2(100 BYTE),
  INVOICE_REF1       VARCHAR2(100 BYTE),
  INVOICE_REF2       VARCHAR2(100 BYTE),
  CREATE_DATE        DATE,
  OPREATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  ORDER_TYPE         VARCHAR2(30 BYTE),
  ORDER_NUMBER       VARCHAR2(20 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(30 BYTE),
  ORDER_REF1         VARCHAR2(100 BYTE),
  ORDER_REF2         VARCHAR2(100 BYTE),
  ORDER_REF3         VARCHAR2(100 BYTE),
  STATUS             CHAR(1 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  UPL_CNT            NUMBER
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON DSS.DSS_FILE_SERIALS_BK04042019 TO SELDATA;
