ALTER TABLE DSS.DSS_BULK_SCAN_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_BULK_SCAN_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_BULK_SCAN_CONFIG
(
  SEQNO              NUMBER,
  ORG_ID             NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(100 BYTE),
  BRAND_SEQ          NUMBER,
  BRAND_NAME         VARCHAR2(50 BYTE),
  MODEL_SEQ          NUMBER,
  MODEL_NAME         VARCHAR2(50 BYTE),
  CONFIG_ID          NUMBER,
  CONFIG_NAME        VARCHAR2(100 BYTE),
  CREATE_DATE        DATE,
  CREATE_BY          VARCHAR2(50 BYTE),
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_BULK_SCAN_CONFIG_PK ON DSS.DSS_BULK_SCAN_CONFIG
(SEQNO)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_BULK_SCAN_CONFIG_U01 ON DSS.DSS_BULK_SCAN_CONFIG
(ORG_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_BULK_SCAN_CONFIG_TRG1
BEFORE INSERT
ON DSS.DSS_BULK_SCAN_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE 
BEGIN  
   :new.SEQNO := SEQ_BULK_SCAN_CONFIG.NEXTVAL;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;
/


ALTER TABLE DSS.DSS_BULK_SCAN_CONFIG ADD (
  CONSTRAINT DSS_BULK_SCAN_CONFIG_PK
  PRIMARY KEY
  (ORG_ID, INVENTORY_ITEM_ID)
  USING INDEX DSS.DSS_BULK_SCAN_CONFIG_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_BULK_SCAN_CONFIG TO SELDATA;
