ALTER TABLE DSS.DSS_STOCK_COUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_STOCK_COUNT CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_STOCK_COUNT
(
  ROW_SEQ        NUMBER,
  LOCATION_CODE  VARCHAR2(10 BYTE),
  PRODUCT_CODE   VARCHAR2(150 BYTE),
  QTY            NUMBER,
  ATTRIBUTE_1    VARCHAR2(100 BYTE),
  ATTRIBUTE_2    VARCHAR2(100 BYTE),
  ATTRIBUTE_3    VARCHAR2(100 BYTE),
  ATTRIBUTE_4    VARCHAR2(100 BYTE),
  ATTRIBUTE_5    VARCHAR2(100 BYTE),
  ATTRIBUTE_6    VARCHAR2(100 BYTE),
  ATTRIBUTE_7    VARCHAR2(100 BYTE),
  ATTRIBUTE_8    VARCHAR2(100 BYTE),
  ATTRIBUTE_9    VARCHAR2(100 BYTE),
  ATTRIBUTE_10   VARCHAR2(100 BYTE),
  CREATED_BY     VARCHAR2(100 BYTE),
  CREATED_DATE   DATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_STOCK_COUNT_PK ON DSS.DSS_STOCK_COUNT
(ROW_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_STOCK_COUNT_TRG
BEFORE INSERT
ON DSS.DSS_STOCK_COUNT
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROW_SEQ
  :new.ROW_SEQ := DSS_STOCK_COUNT_SEQ.nextval;
END DSS_STOCK_COUNT_TRG;
/


ALTER TABLE DSS.DSS_STOCK_COUNT ADD (
  CONSTRAINT DSS_STOCK_COUNT_PK
  PRIMARY KEY
  (ROW_SEQ)
  USING INDEX DSS.DSS_STOCK_COUNT_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_STOCK_COUNT TO SELDATA;
