ALTER TABLE DSS.DSS_FILE_SERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_FILE_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_FILE_SERIALS
(
  ROWSEQ             NUMBER                     NOT NULL,
  FILE_SEQ           NUMBER,
  COUNTRY_CODE       VARCHAR2(50 BYTE)          NOT NULL,
  UPL_SEQ            NUMBER,
  PARENTKEY          VARCHAR2(50 BYTE),
  ISPARENT           CHAR(1 BYTE)               DEFAULT 'N',
  KEYID              NUMBER,
  SERIALKEY          VARCHAR2(50 BYTE),
  BRAND              VARCHAR2(100 BYTE),
  PART_CODE1         VARCHAR2(50 BYTE),
  PART_CODE2         VARCHAR2(50 BYTE),
  EAN_CODE1          VARCHAR2(50 BYTE),
  EAN_CODE2          VARCHAR2(100 BYTE),
  MODEL_CODE1        VARCHAR2(100 BYTE),
  MODEL_CODE2        VARCHAR2(100 BYTE),
  INVOICE_NO         VARCHAR2(100 BYTE),
  INVOICE_REF1       VARCHAR2(100 BYTE),
  INVOICE_REF2       VARCHAR2(100 BYTE),
  CREATE_DATE        DATE                       DEFAULT SYSDATE,
  OPREATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  ORDER_TYPE         VARCHAR2(30 BYTE),
  ORDER_NUMBER       VARCHAR2(20 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(30 BYTE),
  ORDER_REF1         VARCHAR2(100 BYTE),
  ORDER_REF2         VARCHAR2(100 BYTE),
  ORDER_REF3         VARCHAR2(100 BYTE),
  STATUS             CHAR(1 BYTE)               DEFAULT 'N',
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  UPL_CNT            NUMBER                     DEFAULT 1
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (CREATE_DATE)
SUBPARTITION BY LIST (COUNTRY_CODE)
(  
  PARTITION P_FLS_2018 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2018_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_OTH VALUES (default)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2019 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2019_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_OTH VALUES (default)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2020 VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2020_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2021 VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2021_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2022 VALUES LESS THAN (TO_DATE(' 2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2022_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2023 VALUES LESS THAN (TO_DATE(' 2024-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2023_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2024 VALUES LESS THAN (TO_DATE(' 2025-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2024_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2025 VALUES LESS THAN (TO_DATE(' 2026-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2025_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2100 VALUES LESS THAN (MAXVALUE)
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2100_UAE VALUES ('UAE')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_KSA VALUES ('KSA')
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_OTH VALUES (DEFAULT)
     TABLESPACE AXM_TS_WMS )
)
NOCACHE
MONITORING;


CREATE INDEX DSS.IDX_FLS_KEYID ON DSS.DSS_FILE_SERIALS
(KEYID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.IDX_FLS_PARENTKEY ON DSS.DSS_FILE_SERIALS
(PARENTKEY)
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
LOCAL (  
  PARTITION P_FLS_2018
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2018_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2018_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2019
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2019_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2019_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2020
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2020_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2020_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2021
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2021_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2021_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2022
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2022_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2022_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2023
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2023_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2023_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2024
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2024_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2024_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2025
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2025_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2025_OTH
     TABLESPACE AXM_TS_WMS ),  
  PARTITION P_FLS_2100
    NOCOMPRESS 
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  (SUBPARTITION P_FLS_2100_UAE
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_KSA
     TABLESPACE AXM_TS_WMS,
   SUBPARTITION P_FLS_2100_OTH
     TABLESPACE AXM_TS_WMS )
);

CREATE UNIQUE INDEX DSS.PK_ROWSEQ ON DSS.DSS_FILE_SERIALS
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.UDX_FLS_PARENT_KEY_ID ON DSS.DSS_FILE_SERIALS
(PARENTKEY, KEYID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.UK_FLS_SERIALKEY ON DSS.DSS_FILE_SERIALS
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_FILE_SERIALS_TRG
BEFORE INSERT
ON DSS.DSS_FILE_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_FILE_SERIALS_SEQ.nextval;
END DSS_FILE_SERIALS_TRG;
/


ALTER TABLE DSS.DSS_FILE_SERIALS ADD (
  CONSTRAINT PK_ROWSEQ
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.PK_ROWSEQ
  ENABLE VALIDATE,
  CONSTRAINT UK_FLS_SERIALKEY
  UNIQUE (SERIALKEY)
  USING INDEX DSS.UK_FLS_SERIALKEY
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_FILE_SERIALS TO SELDATA;
