ALTER TABLE DSS.DSS_ROW_DELIMITER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ROW_DELIMITER CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ROW_DELIMITER
(
  LINEID  NUMBER,
  NAME    VARCHAR2(100 BYTE),
  VALUE   VARCHAR2(20 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ROW_DELIMITER_PK ON DSS.DSS_ROW_DELIMITER
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_ROW_DELIMITER_TRG
BEFORE INSERT
ON DSS.DSS_ROW_DELIMITER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := SEQ_ROW_DELIMITER_ID.nextval;
END DSS_ROW_DELIMITER_TRG;
/


ALTER TABLE DSS.DSS_ROW_DELIMITER ADD (
  CONSTRAINT DSS_ROW_DELIMITER_PK
  PRIMARY KEY
  (LINEID)
  USING INDEX DSS.DSS_ROW_DELIMITER_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_ROW_DELIMITER TO SELDATA;
