ALTER TABLE DSS.DSS_INTERFACE_PROCESS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_INTERFACE_PROCESS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_INTERFACE_PROCESS
(
  INTERFACEID    NUMBER,
  DESCRIPTION    VARCHAR2(100 BYTE),
  LAST_RUN_DATE  DATE,
  ROW_COUNT      NUMBER,
  STATUS         CHAR(1 BYTE),
  STARTDATE      DATE                           DEFAULT sysdate,
  ENDDATE        DATE                           DEFAULT sysdate
)
TABLESPACE TS_ORABRIDGE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_INTERFACE_PROCESS_PK ON DSS.DSS_INTERFACE_PROCESS
(INTERFACEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_INTERFACE_PROCESS_TRG
BEFORE INSERT
ON DSS.DSS_INTERFACE_PROCESS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column INTERFACEID
  :new.INTERFACEID := SEQ_DSS_INTERFACE_PROCESS.nextval;
END DSS_INTERFACE_PROCESS_TRG;
/


ALTER TABLE DSS.DSS_INTERFACE_PROCESS ADD (
  CONSTRAINT DSS_INTERFACE_PROCESS_PK
  PRIMARY KEY
  (INTERFACEID)
  USING INDEX DSS.DSS_INTERFACE_PROCESS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_INTERFACE_PROCESS TO SELDATA;

GRANT SELECT, UPDATE ON DSS.DSS_INTERFACE_PROCESS TO XXREPDSS;
