ALTER TABLE DSS.DSS_ITEM_CATEGORIES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ITEM_CATEGORIES CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ITEM_CATEGORIES
(
  CATEGORY_ID            NUMBER                 NOT NULL,
  ORGANIZATION_ID        NUMBER                 NOT NULL,
  INVENTORY_ITEM_ID      NUMBER                 NOT NULL,
  CATEGORY_SET_NAME      VARCHAR2(30 BYTE)      NOT NULL,
  CATEGORY_CONCAT_SEGS   VARCHAR2(204 BYTE),
  BRAND_CODE             VARCHAR2(40 BYTE),
  CATEGORY_CODE          VARCHAR2(40 BYTE),
  SUB_CATEGORY_CODE      VARCHAR2(40 BYTE),
  SUB_SUB_CATEGORY_CODE  VARCHAR2(40 BYTE),
  PURCHASETYPE           VARCHAR2(40 BYTE),
  ENABLED                VARCHAR2(1 BYTE)       NOT NULL,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  CREATION_DATE          DATE                   NOT NULL
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ITEM_CATEGORIES_PK ON DSS.DSS_ITEM_CATEGORIES
(INVENTORY_ITEM_ID, ORGANIZATION_ID, CATEGORY_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_ITEM_CATEGORIES ADD (
  CONSTRAINT DSS_ITEM_CATEGORIES_PK
  PRIMARY KEY
  (INVENTORY_ITEM_ID, ORGANIZATION_ID, CATEGORY_ID)
  USING INDEX DSS.DSS_ITEM_CATEGORIES_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_ITEM_CATEGORIES TO SELDATA;
