ALTER TABLE DSS.DSS_ORDER_SERIALS_TEMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_ORDER_SERIALS_TEMP CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ORDER_SERIALS_TEMP
(
  SCANID              NUMBER,
  JOBID               NUMBER,
  LINEID              NUMBER,
  SEQINDEX            NUMBER,
  COLUMNINDEX         NUMBER,
  CONFIGID            NUMBER,
  CONFIGTYPE          VARCHAR2(100 BYTE),
  SCANTYPE            VARCHAR2(100 BYTE),
  SCAN_SOURCE         VARCHAR2(100 BYTE),
  OPREATING_UNIT      NUMBER,
  ORGANIZATION_ID     NUMBER,
  ORDER_TYPE          VARCHAR2(30 BYTE),
  ORDER_NUMBER        VARCHAR2(20 BYTE),
  INVENTORY_ITEM_ID   NUMBER,
  PRODUCT_CODE        VARCHAR2(30 BYTE),
  SERVICE_BRANDID     NUMBER,
  SERIALKEY           VARCHAR2(100 BYTE),
  SERIALKEY_REF1      VARCHAR2(100 BYTE),
  SERIALKEY_REF2      VARCHAR2(100 BYTE),
  WARRANTYPRINT_YN    VARCHAR2(1 BYTE)          DEFAULT 'N',
  WARRANTY_YN         VARCHAR2(1 BYTE)          DEFAULT 'N',
  WARRANTY_SEQ        NUMBER,
  WARRANTY_CODE       VARCHAR2(30 BYTE),
  WARRANTY_STARTDATE  DATE                      DEFAULT SYSDATE,
  WARRANTY_ENDATE     DATE,
  ACTIVE_YN           VARCHAR2(1 BYTE)          DEFAULT 'N',
  INF_YN              VARCHAR2(1 BYTE)          DEFAULT 'N',
  INF_DATE            DATE,
  CREATE_BY           VARCHAR2(20 BYTE),
  CREATE_DATE         DATE                      DEFAULT SYSDATE,
  UPDATE_BY           VARCHAR2(20 BYTE),
  UPDATE_DATE         DATE                      DEFAULT SYSDATE,
  ALLOW_EDIT          CHAR(1 BYTE),
  ATTRIBUTE1          VARCHAR2(100 BYTE),
  ATTRIBUTE2          VARCHAR2(100 BYTE),
  ATTRIBUTE3          VARCHAR2(100 BYTE),
  ATTRIBUTE4          VARCHAR2(100 BYTE),
  ATTRIBUTE5          VARCHAR2(100 BYTE),
  ATTRIBUTE6          VARCHAR2(100 BYTE),
  ATTRIBUTE7          VARCHAR2(100 BYTE),
  ATTRIBUTE8          VARCHAR2(100 BYTE),
  ATTRIBUTE9          VARCHAR2(100 BYTE),
  ATTRIBUTE10         VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_ORDER_SERIALS_TEMP_PK ON DSS.DSS_ORDER_SERIALS_TEMP
(SCANID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_ORDER_SERIALS_TEMP_TRG
BEFORE INSERT
ON DSS.DSS_ORDER_SERIALS_TEMP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SCANID
  :new.SCANID := DSS_ORDER_SERIALS_TEMP_SEQ.nextval;
END DSS_ORDER_SERIALS_TEMP_TRG;
/


ALTER TABLE DSS.DSS_ORDER_SERIALS_TEMP ADD (
  CONSTRAINT DSS_ORDER_SERIALS_TEMP_PK
  PRIMARY KEY
  (SCANID)
  USING INDEX DSS.DSS_ORDER_SERIALS_TEMP_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_ORDER_SERIALS_TEMP TO SELDATA;
