ALTER TABLE DSS.DSS_LOG_INF_PHONECARE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DSS_LOG_INF_PHONECARE CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_LOG_INF_PHONECARE
(
  LOGID           NUMBER,
  OPERATING_UNIT  VARCHAR2(20 BYTE),
  ERROR_ON        VARCHAR2(100 BYTE),
  ERROR_CODE      VARCHAR2(100 BYTE),
  ERROR_MESSAGE   VARCHAR2(200 BYTE),
  STATUS          VARCHAR2(10 BYTE),
  RUN_DATE        DATE,
  ATTRIBUTE1      VARCHAR2(50 BYTE),
  ATTRIBUTE2      VARCHAR2(50 BYTE),
  ATTRIBUTE3      VARCHAR2(50 BYTE),
  ATTRIBUTE4      VARCHAR2(50 BYTE),
  ATTRIBUTE5      VARCHAR2(50 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_LOG_INF_PHONECARE_PK ON DSS.DSS_LOG_INF_PHONECARE
(LOGID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.DSS_LOG_INF_PHONECARE ADD (
  CONSTRAINT DSS_LOG_INF_PHONECARE_PK
  PRIMARY KEY
  (LOGID)
  USING INDEX DSS.DSS_LOG_INF_PHONECARE_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_LOG_INF_PHONECARE TO SELDATA;
