DROP TABLE DSS.DSS_SALES_UPLD_DTL CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_SALES_UPLD_DTL
(
  HEADERSEQ          NUMBER,
  LINESEQ            NUMBER,
  OPERATING_UNIT     NUMBER                     NOT NULL,
  ORGANIZATION_ID    NUMBER                     NOT NULL,
  LOCATION_CODE      VARCHAR2(10 BYTE)          NOT NULL,
  TRANSACTION_NO     VARCHAR2(50 BYTE)          NOT NULL,
  TRANSACTION_DATE   DATE                       NOT NULL,
  TRANSACTION_TYPE   VARCHAR2(50 BYTE)          NOT NULL,
  LINE_NUM           NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(50 BYTE),
  PRODUCT_UOM        VARCHAR2(10 BYTE)          NOT NULL,
  QTY                NUMBER(8)                  NOT NULL,
  LC_PRICE           NUMBER(17,3)               NOT NULL,
  STATUS             CHAR(1 BYTE)               DEFAULT 'P',
  INTF_YN            CHAR(1 BYTE)               DEFAULT 'N',
  CREATE_DATE        DATE                       NOT NULL,
  CREATE_BY          VARCHAR2(100 BYTE),
  MODIFY_DATE        DATE                       NOT NULL,
  MODIFY_BY          VARCHAR2(100 BYTE),
  ITEM_TYPE          VARCHAR2(10 BYTE),
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE),
  ATTRIBUTE8         VARCHAR2(100 BYTE),
  ATTRIBUTE9         VARCHAR2(100 BYTE),
  ATTRIBUTE10        VARCHAR2(100 BYTE),
  ATTRIBUTE11        VARCHAR2(100 BYTE),
  ATTRIBUTE12        VARCHAR2(100 BYTE),
  ATTRIBUTE13        VARCHAR2(100 BYTE),
  ATTRIBUTE14        VARCHAR2(100 BYTE),
  ATTRIBUTE15        VARCHAR2(100 BYTE),
  RESATTRIBUTE1      VARCHAR2(500 BYTE),
  RESATTRIBUTE2      VARCHAR2(500 BYTE),
  RESATTRIBUTE3      VARCHAR2(500 BYTE),
  TAX_RATE_ID        NUMBER,
  TAX_VALUE          NUMBER,
  TAX_PERCENTAGE     NUMBER,
  TOTAL_PRICE        NUMBER
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.DSS_SALES_UPLD_DTL_PK ON DSS.DSS_SALES_UPLD_DTL
(LINESEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.DSS_SALES_UPLD_DTL_U01 ON DSS.DSS_SALES_UPLD_DTL
(LINE_NUM, HEADERSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_SALES_UPLD_DTL_TRG
BEFORE INSERT
ON DSS.DSS_SALES_UPLD_DTL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINESEQ
  :new.LINESEQ := SEQ_SALES_UPLD_DTL.nextval;
END DSS_SALES_UPLD_DTL_TRG;
/


ALTER TABLE DSS.DSS_SALES_UPLD_DTL ADD (
  CONSTRAINT DSS_SALES_UPLD_DTL_U01
  UNIQUE (LINE_NUM, HEADERSEQ)
  USING INDEX DSS.DSS_SALES_UPLD_DTL_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DSS_SALES_UPLD_DTL TO SELDATA;
