DROP TABLE DSS.DSS_ACTIVATION_SERIAL_LOG CASCADE CONSTRAINTS;

CREATE TABLE DSS.DSS_ACTIVATION_SERIAL_LOG
(
  ROWSEQ           NUMBER                       NOT NULL,
  FILE_SEQ         NUMBER,
  ACTIVE_CNT       NUMBER,
  COUNTRY_CODE     VARCHAR2(50 BYTE),
  BRAND            VARCHAR2(50 BYTE),
  COUNTRY_ID       VARCHAR2(50 BYTE),
  PARENTKEY        VARCHAR2(100 BYTE),
  KEYID            NUMBER,
  SERIALKEY        VARCHAR2(100 BYTE),
  ACTIVATION_DATE  DATE                         DEFAULT SYSDATE,
  ACT_FILE_SEQ     NUMBER,
  CREATE_DATE      DATE                         DEFAULT SYSDATE,
  STATUS           VARCHAR2(3 BYTE)             DEFAULT 'N',
  INTF_STATUS      VARCHAR2(3 BYTE)             DEFAULT 'N',
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DSS.DSS_ACTIVATION_SERIAL_LOG.ACT_FILE_SEQ IS 'Existing file seq in activation serial';


CREATE INDEX DSS.DSS_ACTIVATION_SERIAL_LOG_IND ON DSS.DSS_ACTIVATION_SERIAL_LOG
(ACT_FILE_SEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.DSS_ACTIVATION_SERIAL_LOG_IND1 ON DSS.DSS_ACTIVATION_SERIAL_LOG
(SERIALKEY)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.DSS_ACTIVATION_SERIAL_LOG_TRG
BEFORE INSERT
ON DSS.DSS_ACTIVATION_SERIAL_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := DSS_ACTIVATION_SERIAL_LOG_SEQ.nextval;
END DSS_ACTIVATION_SERIAL_LOG_TRG;
/


GRANT SELECT ON DSS.DSS_ACTIVATION_SERIAL_LOG TO SELDATA;
