ALTER TABLE DSS.DWL_TRANSACTION_SERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.DWL_TRANSACTION_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.DWL_TRANSACTION_SERIALS
(
  ROWSEQ              NUMBER,
  SCE_LINEID          NUMBER,
  FACILITY_CODE       VARCHAR2(100 BYTE),
  BATCHID             NUMBER,
  HEADER_SEQ          NUMBER,
  HEADERID            NUMBER,
  ORDER_TYPE          VARCHAR2(30 BYTE),
  SCE_ORDERTYPE       VARCHAR2(100 BYTE),
  ORDER_NUMBER        VARCHAR2(20 BYTE),
  SCE_PICKDETAILKEY   VARCHAR2(20 BYTE),
  ORDER_REF1          VARCHAR2(100 BYTE),
  ORDER_REF2          VARCHAR2(100 BYTE),
  ORDER_REF3          VARCHAR2(100 BYTE),
  ORDER_REF4          VARCHAR2(100 BYTE),
  SCE_ORDERLINEID     NUMBER,
  LINE_SEQ            NUMBER,
  LINEID              NUMBER,
  OPREATING_UNIT      NUMBER,
  ORGANIZATION_ID     NUMBER,
  SUBINVENTORY_CODE   VARCHAR2(100 BYTE),
  LOCATION_CODE       VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID   NUMBER,
  PRODUCT_CODE        VARCHAR2(50 BYTE),
  CATEGORYID          NUMBER,
  BRANDCODE           VARCHAR2(100 BYTE),
  MODELCODE           VARCHAR2(100 BYTE),
  SEQINDEX            NUMBER,
  KEYID               NUMBER,
  SCANTYPE            VARCHAR2(100 BYTE),
  SCAN_SOURCE         VARCHAR2(100 BYTE),
  SERIALKEY           VARCHAR2(100 BYTE),
  SERIALKEY_REF1      VARCHAR2(100 BYTE),
  SERIALKEY_REF2      VARCHAR2(100 BYTE),
  SERIALKEY_REF3      VARCHAR2(100 BYTE),
  SERIALKEY_REF4      VARCHAR2(100 BYTE),
  SERVICE_BRANDID     NUMBER,
  WARRANTY_YN         VARCHAR2(3 BYTE)          DEFAULT 'N',
  WARRANTY_INFO       VARCHAR2(100 BYTE),
  WARRANTY_SEQ        NUMBER,
  WARRANTY_CODE       VARCHAR2(30 BYTE),
  WARRANTY_STARTDATE  DATE                      DEFAULT SYSDATE,
  WARRANTY_ENDATE     DATE,
  INF_STATUS          VARCHAR2(1 BYTE)          DEFAULT 'N',
  INF_DATE            DATE,
  INF_MESSAGE         VARCHAR2(500 BYTE)        DEFAULT 'N',
  CREATE_BY           VARCHAR2(20 BYTE),
  CREATE_DATE         DATE                      DEFAULT SYSDATE,
  ATTRIBUTE1          VARCHAR2(100 BYTE),
  ATTRIBUTE2          VARCHAR2(100 BYTE),
  ATTRIBUTE3          VARCHAR2(100 BYTE),
  ATTRIBUTE4          VARCHAR2(100 BYTE),
  ATTRIBUTE5          VARCHAR2(100 BYTE),
  ATTRIBUTE6          VARCHAR2(100 BYTE),
  ATTRIBUTE7          VARCHAR2(100 BYTE),
  ATTRIBUTE8          VARCHAR2(100 BYTE),
  ATTRIBUTE9          VARCHAR2(100 BYTE),
  ATTRIBUTE10         VARCHAR2(100 BYTE)
)
NOCOMPRESS 
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (CREATE_DATE)
(  
  PARTITION SERIALS_2017_Q3 VALUES LESS THAN (TO_DATE(' 2017-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2017_Q4 VALUES LESS THAN (TO_DATE(' 2018-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q1 VALUES LESS THAN (TO_DATE(' 2018-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          8M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q2 VALUES LESS THAN (TO_DATE(' 2018-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q3 VALUES LESS THAN (TO_DATE(' 2018-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2018_Q4 VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q1 VALUES LESS THAN (TO_DATE(' 2019-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q2 VALUES LESS THAN (TO_DATE(' 2019-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q3 VALUES LESS THAN (TO_DATE(' 2019-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_2019_Q4 VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION SERIALS_MAX VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCACHE
MONITORING;


--  There is no statement for index DSS.SYS_C00654193.
--  The object is created when the parent object is created.

--  There is no statement for index DSS.SYS_C00654194.
--  The object is created when the parent object is created.

ALTER TABLE DSS.DWL_TRANSACTION_SERIALS ADD (
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE,
  UNIQUE (ORDER_TYPE, ORDER_NUMBER, PRODUCT_CODE, KEYID, SERIALKEY)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

GRANT SELECT ON DSS.DWL_TRANSACTION_SERIALS TO SELDATA;
