ALTER TABLE DSS.INTM_VALIDATION_KEYS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.INTM_VALIDATION_KEYS CASCADE CONSTRAINTS;

CREATE TABLE DSS.INTM_VALIDATION_KEYS
(
  RULEID         NUMBER,
  KEYID          NUMBER,
  KEYNAME        VARCHAR2(100 BYTE),
  UNIQUE_KEY     INTEGER                        DEFAULT 0,
  NUMERIC_KEY    INTEGER                        DEFAULT 0,
  MAX_LENGTH     NUMBER,
  MIN_LENGTH     NUMBER,
  LUHN_KEY       INTEGER                        DEFAULT 0,
  SPECIAL_CHARS  INTEGER,
  CAPTURE        INTEGER                        DEFAULT 1,
  CREATE_DATE    DATE                           DEFAULT SYSDATE,
  CREATE_BY      VARCHAR2(100 BYTE),
  MODIFYDATE     DATE                           DEFAULT SYSDATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.INTM_VALIDATION_KEYS_PK ON DSS.INTM_VALIDATION_KEYS
(RULEID, KEYID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.INTM_VALIDATION_KEYS ADD (
  CONSTRAINT INTM_VALIDATION_KEYS_PK
  PRIMARY KEY
  (RULEID, KEYID)
  USING INDEX DSS.INTM_VALIDATION_KEYS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.INTM_VALIDATION_KEYS TO SELDATA;
