ALTER TABLE DSS.INTM_VALIDATION_RULES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.INTM_VALIDATION_RULES CASCADE CONSTRAINTS;

CREATE TABLE DSS.INTM_VALIDATION_RULES
(
  RULEID           NUMBER,
  RULE_NAME        VARCHAR2(100 BYTE),
  RULE_CODE        VARCHAR2(50 BYTE),
  RULE_PARAMETERS  VARCHAR2(1000 BYTE),
  RULE_TYPE        VARCHAR2(50 BYTE),
  CREATE_DATE      DATE                         DEFAULT SYSDATE,
  CREATE_BY        VARCHAR2(100 BYTE),
  MODIFYDATE       DATE                         DEFAULT SYSDATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.INTM_VALIDATION_RULES_PK ON DSS.INTM_VALIDATION_RULES
(RULEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.INTM_VALIDATION_RULES_TRG
   BEFORE INSERT
   ON DSS.INTM_VALIDATION_RULES
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column RULEID
   :new.RULEID := SEQ_VALIDATION_RULES.NEXTVAL;
--- :new.RULE_PARAMETERS := CONCAT (:new.RULEID, ',' || :new.RULE_PARAMETERS);
END INTM_VALIDATION_RULES_TRG;
/


ALTER TABLE DSS.INTM_VALIDATION_RULES ADD (
  CONSTRAINT INTM_VALIDATION_RULES_PK
  PRIMARY KEY
  (RULEID)
  USING INDEX DSS.INTM_VALIDATION_RULES_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.INTM_VALIDATION_RULES TO SELDATA;
