ALTER TABLE DSS.INTM_PRODUCTS_VALIDATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.INTM_PRODUCTS_VALIDATION CASCADE CONSTRAINTS;

CREATE TABLE DSS.INTM_PRODUCTS_VALIDATION
(
  ROWSEQ             NUMBER,
  ORGANIZATION_ID    NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  KEYS_CONFIG        VARCHAR2(500 BYTE),
  RULEID             NUMBER,
  CREATE_DATE        DATE                       DEFAULT SYSDATE,
  CREATE_BY          VARCHAR2(100 BYTE),
  MODIFY_DATE        DATE                       DEFAULT SYSDATE
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.INTM_PRODUCTS_VALIDATION_PK ON DSS.INTM_PRODUCTS_VALIDATION
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.INTM_PRODUCTS_VALIDATION_TRG
BEFORE INSERT
ON DSS.INTM_PRODUCTS_VALIDATION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := SEQ_PRODUCTS_VALIDATION.nextval;
END INTM_PRODUCTS_VALIDATION_TRG;
/


ALTER TABLE DSS.INTM_PRODUCTS_VALIDATION ADD (
  CONSTRAINT INTM_PRODUCTS_VALIDATION_PK
  PRIMARY KEY
  (ORGANIZATION_ID, INVENTORY_ITEM_ID)
  USING INDEX DSS.INTM_PRODUCTS_VALIDATION_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.INTM_PRODUCTS_VALIDATION TO SELDATA;
