ALTER TABLE DSS.PAYOUT_IMEI_VALIDATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.PAYOUT_IMEI_VALIDATION CASCADE CONSTRAINTS;

CREATE TABLE DSS.PAYOUT_IMEI_VALIDATION
(
  ROWSEQ       NUMBER,
  BATCHID      NUMBER,
  BATCHCODE    VARCHAR2(100 BYTE),
  IMEI_NUMBER  NUMBER,
  ISVALID      CHAR(1 BYTE)                     DEFAULT 'N'
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.PAYOUT_IMEI_VALIDATION_PK ON DSS.PAYOUT_IMEI_VALIDATION
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.PAYOUT_IMEI_VALIDATION_TRG
BEFORE INSERT
ON DSS.PAYOUT_IMEI_VALIDATION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := PAYOUT_IMEI_SEQ.nextval;
END PAYOUT_IMEI_VALIDATION_TRG;
/


ALTER TABLE DSS.PAYOUT_IMEI_VALIDATION ADD (
  CONSTRAINT PAYOUT_IMEI_VALIDATION_PK
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.PAYOUT_IMEI_VALIDATION_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.PAYOUT_IMEI_VALIDATION TO SELDATA;
