DROP TABLE DSS.REC_ORDER_SCAN_HEADER CASCADE CONSTRAINTS;

CREATE TABLE DSS.REC_ORDER_SCAN_HEADER
(
  JOBID         NUMBER,
  ORDER_TYPE    VARCHAR2(30 BYTE),
  ORDER_NUMBER  VARCHAR2(20 BYTE),
  HANDLED       CHAR(1 BYTE)                    DEFAULT 'N'
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
