DROP TABLE DSS.REP_CONNECTIONS CASCADE CONSTRAINTS;

CREATE TABLE DSS.REP_CONNECTIONS
(
  LINEID             NUMBER,
  CONNECTION_NAME    VARCHAR2(100 BYTE),
  DATA_PROVIDER      VARCHAR2(100 BYTE),
  CONNCETION_STRING  VARCHAR2(1000 BYTE),
  DEFAULT_SCHEMA     VARCHAR2(100 BYTE),
  FILTER_1           VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER DSS.REP_CONNECTIONS_TRG
BEFORE INSERT
ON DSS.REP_CONNECTIONS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column LINEID
  :new.LINEID := REP_CONNECTIONS_SEQ.nextval;
END REP_CONNECTIONS_TRG;
/


GRANT SELECT ON DSS.REP_CONNECTIONS TO SELDATA;
