ALTER TABLE DSS.RPT_SCAN_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.RPT_SCAN_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE DSS.RPT_SCAN_CONFIG
(
  ROWSEQ         NUMBER,
  CATEGORY_ID    NUMBER,
  CHANNEL        NUMBER,
  ORDER_TYPE     VARCHAR2(100 BYTE),
  ORDER_QTY      NUMBER,
  DELIVERED_QTY  NUMBER,
  SCANNED_QTY    NUMBER,
  PRODUCT_COUNT  NUMBER,
  ORDERNAME      VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.RPT_SCAN_CONFIG_PK ON DSS.RPT_SCAN_CONFIG
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.RPT_SCAN_CONFIG_TRG
BEFORE INSERT
ON DSS.RPT_SCAN_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := RPT_SCAN_CONFIG_SEQ.nextval;
END RPT_SCAN_CONFIG_TRG;
/


ALTER TABLE DSS.RPT_SCAN_CONFIG ADD (
  CONSTRAINT RPT_SCAN_CONFIG_PK
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.RPT_SCAN_CONFIG_PK
  ENABLE VALIDATE);
