ALTER TABLE DSS.RPT_SCAN_ITEM_LEVEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.RPT_SCAN_ITEM_LEVEL CASCADE CONSTRAINTS;

CREATE TABLE DSS.RPT_SCAN_ITEM_LEVEL
(
  ROWSEQ             NUMBER,
  ORGANIZATION_ID    NUMBER,
  ORDER_TYPE         VARCHAR2(30 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  ORDER_QTY          NUMBER,
  DELIVERED_QTY      NUMBER,
  SCANNED            NUMBER,
  PROCESSTYPE        VARCHAR2(100 BYTE),
  ISEXTERNAL         CHAR(1 BYTE)               DEFAULT 'N'
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.RPT_SCAN_ITEM_LEVEL_PK ON DSS.RPT_SCAN_ITEM_LEVEL
(ROWSEQ)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.RPT_SCAN_ITEM_LEVEL_TRG
BEFORE INSERT
ON DSS.RPT_SCAN_ITEM_LEVEL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := RPT_SCAN_ITEM_LEVEL_SEQ.nextval;
END RPT_SCAN_ITEM_LEVEL_TRG;
/


ALTER TABLE DSS.RPT_SCAN_ITEM_LEVEL ADD (
  CONSTRAINT RPT_SCAN_ITEM_LEVEL_PK
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX DSS.RPT_SCAN_ITEM_LEVEL_PK
  ENABLE VALIDATE);
