ALTER TABLE DSS.SEC_USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.SEC_USERS CASCADE CONSTRAINTS;

CREATE TABLE DSS.SEC_USERS
(
  USER_NAME         VARCHAR2(100 BYTE),
  DISPLAY_NAME      VARCHAR2(100 BYTE),
  FIRST_NAME        VARCHAR2(100 BYTE),
  LAST_NAME         VARCHAR2(200 BYTE),
  EMAIL             VARCHAR2(200 BYTE),
  TITLE             VARCHAR2(200 BYTE),
  PERSONAL_TITLE    VARCHAR2(200 BYTE),
  MOBILE_NUMBER     VARCHAR2(200 BYTE),
  PHONE_NUMBER      VARCHAR2(200 BYTE),
  TELEPHONE_NUMBER  VARCHAR2(200 BYTE),
  LOGIN_TYPE        VARCHAR2(100 BYTE),
  OFFLINE_PASSWORD  VARCHAR2(100 BYTE),
  CREATE_DATE       DATE                        DEFAULT SYSDATE,
  LAST_LOGIN_DATE   DATE                        DEFAULT SYSDATE,
  ENABLED           CHAR(1 BYTE)                DEFAULT 'A',
  ATTRIBUTE1        VARCHAR2(200 BYTE),
  ATTRIBUTE2        VARCHAR2(200 BYTE),
  ATTRIBUTE3        VARCHAR2(200 BYTE),
  ATTRIBUTE4        VARCHAR2(200 BYTE),
  ATTRIBUTE5        VARCHAR2(200 BYTE),
  ATTRIBUTE6        VARCHAR2(200 BYTE),
  ATTRIBUTE7        VARCHAR2(200 BYTE),
  ATTRIBUTE8        VARCHAR2(200 BYTE),
  ATTRIBUTE9        VARCHAR2(200 BYTE),
  ATTRIBUTE10       VARCHAR2(200 BYTE)
)
TABLESPACE TS_ORABRIDGE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.SEC_USERS_PK ON DSS.SEC_USERS
(USER_NAME)
LOGGING
TABLESPACE TS_ORABRIDGE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.SEC_USERS ADD (
  CONSTRAINT SEC_USERS_PK
  PRIMARY KEY
  (USER_NAME)
  USING INDEX DSS.SEC_USERS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.SEC_USERS TO SELDATA;
