ALTER TABLE DSS.SEC_USER_FORM_ACCESS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.SEC_USER_FORM_ACCESS CASCADE CONSTRAINTS;

CREATE TABLE DSS.SEC_USER_FORM_ACCESS
(
  USER_NAME    VARCHAR2(100 BYTE),
  FORM_ID      NUMBER,
  MODIFY_DATE  DATE,
  EXPIRY_DATE  DATE                             DEFAULT SYSDATE + 100,
  CREATE_BY    VARCHAR2(100 BYTE),
  CREATE_DATE  DATE                             DEFAULT SYSDATE,
  ENABLED      CHAR(1 BYTE)                     DEFAULT 'Y',
  ATTRIBUTE1   VARCHAR2(100 BYTE),
  ATTRIBUTE2   VARCHAR2(100 BYTE),
  ATTRIBUTE3   VARCHAR2(100 BYTE),
  ATTRIBUTE4   VARCHAR2(100 BYTE),
  ATTRIBUTE5   VARCHAR2(100 BYTE),
  ATTRIBUTE6   VARCHAR2(100 BYTE)
)
TABLESPACE TS_ORABRIDGE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.SEC_USER_FORM_ACCESS_PK ON DSS.SEC_USER_FORM_ACCESS
(FORM_ID, USER_NAME)
LOGGING
TABLESPACE TS_ORABRIDGE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.SEC_USER_FORM_ACCESS ADD (
  CONSTRAINT SEC_USER_FORM_ACCESS_PK
  PRIMARY KEY
  (FORM_ID, USER_NAME)
  USING INDEX DSS.SEC_USER_FORM_ACCESS_PK
  ENABLE VALIDATE);

GRANT SELECT ON DSS.SEC_USER_FORM_ACCESS TO SELDATA;
