ALTER TABLE DSS.SERIAL_UPD_TEMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.SERIAL_UPD_TEMP CASCADE CONSTRAINTS;

CREATE TABLE DSS.SERIAL_UPD_TEMP
(
  ROWSEQ        INTEGER,
  SERIALNUMBER  NVARCHAR2(150)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.SERIAL_UPD_TEMP_PK ON DSS.SERIAL_UPD_TEMP
(ROWSEQ, SERIALNUMBER)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.SERIAL_UPD_TEMP ADD (
  CONSTRAINT SERIAL_UPD_TEMP_PK
  PRIMARY KEY
  (ROWSEQ, SERIALNUMBER)
  USING INDEX DSS.SERIAL_UPD_TEMP_PK
  ENABLE VALIDATE);
