DROP TABLE DSS.TEM_SAMSUNG_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.TEM_SAMSUNG_SERIALS
(
  ROWSEQ        NUMBER,
  PRODUCT_CODE  VARCHAR2(100 BYTE),
  STATUS        CHAR(1 BYTE),
  SERIALKEY     VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
