ALTER TABLE DSS.TEMP_IMEI
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.TEMP_IMEI CASCADE CONSTRAINTS;

CREATE TABLE DSS.TEMP_IMEI
(
  ROWSEQ        INTEGER,
  SERIALNUMBER  NVARCHAR2(150),
  PARENTKEY     NVARCHAR2(150),
  PRODUCTCODE   NVARCHAR2(100),
  ISPARENT      CHAR(1 BYTE),
  HASCHILD      CHAR(1 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.TEMP_IMEI_PK ON DSS.TEMP_IMEI
(ROWSEQ, SERIALNUMBER)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER DSS.TEMP_IMEI_TRG
BEFORE INSERT
ON DSS.TEMP_IMEI
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_IMEI_SEQ.nextval;
END TEMP_IMEI_TRG;
/


ALTER TABLE DSS.TEMP_IMEI ADD (
  CONSTRAINT TEMP_IMEI_PK
  PRIMARY KEY
  (ROWSEQ, SERIALNUMBER)
  USING INDEX DSS.TEMP_IMEI_PK
  ENABLE VALIDATE);
