DROP TABLE DSS.TEMP_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.TEMP_SERIALS
(
  SERIALKEY      VARCHAR2(100 BYTE)             NOT NULL,
  PARENTKEY      VARCHAR2(100 BYTE),
  PRODUCT_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  ISPARENT       CHAR(1 BYTE),
  HASCHILD       CHAR(1 BYTE),
  LAST_SCANDATE  DATE,
  CREATE_DATE    DATE,
  UPDATE_CNT     NUMBER
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
