DROP TABLE DSS.TEMP_SAM_ACC_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.TEMP_SAM_ACC_SERIALS
(
  ROWSEQ          NUMBER,
  MONTHYEAR       VARCHAR2(100 BYTE),
  SERIALNO        VARCHAR2(100 BYTE),
  MATERIALNUMBER  VARCHAR2(100 BYTE),
  AXIOMCODE       VARCHAR2(100 BYTE),
  DOCUMENTNO      VARCHAR2(100 BYTE),
  BILLINGNO       VARCHAR2(100 BYTE),
  SHIPTOPARTY     VARCHAR2(100 BYTE),
  SONO            VARCHAR2(100 BYTE),
  REFERENCENAME1  VARCHAR2(100 BYTE),
  REFERENCENAME2  VARCHAR2(100 BYTE),
  COMPANYNAME     VARCHAR2(100 BYTE),
  SALESORG        VARCHAR2(100 BYTE),
  ACTUALGIDATE    VARCHAR2(100 BYTE),
  REFERENCECODE1  VARCHAR2(100 BYTE),
  REFERENCECODE2  VARCHAR2(100 BYTE),
  REFERENCETYPE2  VARCHAR2(100 BYTE),
  SHIPTOCOUNTRY   VARCHAR2(100 BYTE),
  SOLDTOPARTY     VARCHAR2(100 BYTE),
  ORDERTYPETEXT   VARCHAR2(100 BYTE),
  BILLINGDATE     VARCHAR2(100 BYTE),
  CUSTOMERPO      VARCHAR2(100 BYTE),
  CREATEDBY       VARCHAR2(100 BYTE),
  CREATEDDATE     VARCHAR2(100 BYTE),
  HASERROR        CHAR(1 BYTE),
  ERRORCODES      VARCHAR2(100 BYTE),
  ERP_PO_NO       VARCHAR2(100 BYTE),
  ACTUAL_DATE     DATE,
  PO_HEADER_ID    VARCHAR2(100 BYTE),
  VENDOR_ID       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER DSS.TEMP_SAM_ACC_SERIALS_TRG
BEFORE INSERT
ON DSS.TEMP_SAM_ACC_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_SAM_ACC_SERIALS_SEQ.nextval;
END TEMP_SAM_ACC_SERIALS_TRG;
/
