ALTER TABLE DSS.TEMP_FILE_SERIALS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.TEMP_FILE_SERIALS CASCADE CONSTRAINTS;

CREATE TABLE DSS.TEMP_FILE_SERIALS
(
  ROWSEQ           NUMBER,
  COUNTRYCODE      VARCHAR2(100 BYTE),
  FILE_SEQ         NUMBER,
  PARENTKEY        VARCHAR2(50 BYTE),
  SERIAL_KEY_1     VARCHAR2(50 BYTE),
  SERIAL_KEY_2     VARCHAR2(50 BYTE),
  SERIAL_KEY_3     VARCHAR2(50 BYTE),
  SERIAL_KEY_4     VARCHAR2(50 BYTE),
  BRAND            VARCHAR2(100 BYTE),
  PART_CODE1       VARCHAR2(50 BYTE),
  PART_CODE2       VARCHAR2(50 BYTE),
  EAN_CODE1        VARCHAR2(100 BYTE),
  EAN_CODE2        VARCHAR2(100 BYTE),
  MODEL_CODE1      VARCHAR2(100 BYTE),
  MODEL_CODE2      VARCHAR2(100 BYTE),
  INVOICE_NO       VARCHAR2(100 BYTE),
  INVOICE_REF1     VARCHAR2(100 BYTE),
  INVOICE_REF2     VARCHAR2(100 BYTE),
  CREATE_DATE      DATE,
  AX_PRODUCT_CODE  VARCHAR2(100 BYTE),
  AX_ORDER_TYPE    VARCHAR2(100 BYTE),
  AX_ORDER_NO      VARCHAR2(100 BYTE),
  AX_ORDER_REF1    VARCHAR2(100 BYTE),
  AX_ORDER_REF2    VARCHAR2(100 BYTE),
  AX_ORDER_REF3    VARCHAR2(100 BYTE),
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index DSS.SYS_C00778175.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER DSS.TEMP_FILE_SERIALS_TRG
BEFORE INSERT
ON DSS.TEMP_FILE_SERIALS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ROWSEQ
  :new.ROWSEQ := TEMP_FILE_SERIALS_SEQ.nextval;
END TEMP_FILE_SERIALS_TRG;
/


ALTER TABLE DSS.TEMP_FILE_SERIALS ADD (
  PRIMARY KEY
  (ROWSEQ)
  USING INDEX
    TABLESPACE AXM_TS_WMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

GRANT SELECT ON DSS.TEMP_FILE_SERIALS TO SELDATA;
