ALTER TABLE DSS.TK_CATEGORIES_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.TK_CATEGORIES_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE DSS.TK_CATEGORIES_CONFIG
(
  CATEGORY_ID            NUMBER                 NOT NULL,
  BRAND                  VARCHAR2(40 BYTE),
  CATEGORY_CODE          VARCHAR2(40 BYTE),
  SUB_CATEGORY_CODE      VARCHAR2(40 BYTE),
  SUB_SUB_CATEGORY_CODE  VARCHAR2(40 BYTE),
  PURCHASETYPE           VARCHAR2(40 BYTE),
  CATEGORY_CONCAT_SEGS   VARCHAR2(204 BYTE),
  UNIQUE_KEY             CHAR(1 BYTE)           DEFAULT 'N',
  NUMERIC_KEY            CHAR(1 BYTE)           DEFAULT 'N',
  CHECK_BARCODE          CHAR(1 BYTE)           DEFAULT 'N',
  IMEI_KEY               CHAR(1 BYTE)           DEFAULT 'N',
  ALLOW_SPECIALCHAR      CHAR(1 BYTE)           DEFAULT 'Y',
  IMEI_LENGTH_MAX        NUMBER                 DEFAULT 0,
  IMEI_LENGTH_MIN        NUMBER                 DEFAULT 0,
  SCAN_REQUIRED          CHAR(1 BYTE)           DEFAULT 'N',
  ENABLED                CHAR(1 BYTE)           DEFAULT 'N',
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  CREATION_DATE          DATE                   NOT NULL,
  ATTRIBUTE1             VARCHAR2(200 BYTE),
  ATTRIBUTE2             VARCHAR2(200 BYTE),
  ATTRIBUTE3             VARCHAR2(200 BYTE),
  ATTRIBUTE4             VARCHAR2(200 BYTE),
  ATTRIBUTE5             VARCHAR2(200 BYTE),
  ATTRIBUTE6             VARCHAR2(200 BYTE),
  ATTRIBUTE7             VARCHAR2(200 BYTE),
  ATTRIBUTE8             VARCHAR2(200 BYTE),
  ATTRIBUTE9             VARCHAR2(200 BYTE)     DEFAULT 'Y',
  ATTRIBUTE10            VARCHAR2(200 BYTE)     DEFAULT 'N',
  ALLOWNULL              CHAR(1 BYTE)           DEFAULT 'Y'
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DSS.TK_CATEGORIES_CONFIG.ATTRIBUTE8 IS 'This Table Used for Moving to Rule ID ';

COMMENT ON COLUMN DSS.TK_CATEGORIES_CONFIG.ATTRIBUTE9 IS 'This Column to Know if the warranty can be applied to or not 
N= Not eligible 
Y or Null  = eligible';

COMMENT ON COLUMN DSS.TK_CATEGORIES_CONFIG.ATTRIBUTE10 IS 'PRINT WARRANTY Y/N ';


CREATE UNIQUE INDEX DSS.DSS_CATEGORIES_CONFIG_PK ON DSS.TK_CATEGORIES_CONFIG
(CATEGORY_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX DSS.TK_CATEGORIES_CONFIG_IX2 ON DSS.TK_CATEGORIES_CONFIG
(CATEGORY_ID, CATEGORY_CODE, SUB_CATEGORY_CODE, SUB_SUB_CATEGORY_CODE)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.TK_CATEGORIES_CONFIG_U01 ON DSS.TK_CATEGORIES_CONFIG
(PURCHASETYPE, SUB_SUB_CATEGORY_CODE, SUB_CATEGORY_CODE, CATEGORY_CODE, BRAND)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.TK_CATEGORIES_CONFIG ADD (
  CONSTRAINT DSS_CATEGORIES_CONFIG_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX DSS.DSS_CATEGORIES_CONFIG_PK
  ENABLE VALIDATE,
  CONSTRAINT TK_CATEGORIES_CONFIG_U01
  UNIQUE (PURCHASETYPE, SUB_SUB_CATEGORY_CODE, SUB_CATEGORY_CODE, CATEGORY_CODE, BRAND)
  USING INDEX DSS.TK_CATEGORIES_CONFIG_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.TK_CATEGORIES_CONFIG TO SELDATA;
