ALTER TABLE DSS.TK_ORGANIZATION_WARRANTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.TK_ORGANIZATION_WARRANTY CASCADE CONSTRAINTS;

CREATE TABLE DSS.TK_ORGANIZATION_WARRANTY
(
  LINEID           NUMBER,
  OPERATING_UNIT   NUMBER,
  ORGANIZATION_ID  NUMBER,
  CATEGORY_ID      NUMBER,
  WARRANTY_SEQ     NUMBER,
  CREATE_DATE      DATE,
  CREATE_BY        VARCHAR2(30 BYTE),
  ACTIVE           CHAR(1 BYTE)                 DEFAULT 'Y',
  ATTRIBUTE1       VARCHAR2(100 BYTE),
  ATTRIBUTE2       VARCHAR2(100 BYTE),
  ATTRIBUTE3       VARCHAR2(100 BYTE),
  ATTRIBUTE4       VARCHAR2(100 BYTE),
  ATTRIBUTE5       VARCHAR2(100 BYTE),
  ATTRIBUTE6       VARCHAR2(100 BYTE),
  ATTRIBUTE7       VARCHAR2(100 BYTE),
  ATTRIBUTE8       VARCHAR2(100 BYTE),
  ATTRIBUTE9       VARCHAR2(100 BYTE),
  ATTRIBUTE10      VARCHAR2(100 BYTE),
  ATTRIBUTE11      VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.TK_ORGANIZATION_WARRANTY_PK ON DSS.TK_ORGANIZATION_WARRANTY
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.TK_ORGANIZATION_WARRANTY_U01 ON DSS.TK_ORGANIZATION_WARRANTY
(CATEGORY_ID, ORGANIZATION_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.TK_ORGANIZATION_WARRANTY ADD (
  CONSTRAINT TK_ORGANIZATION_WARRANTY_PK
  PRIMARY KEY
  (LINEID)
  USING INDEX DSS.TK_ORGANIZATION_WARRANTY_PK
  ENABLE VALIDATE,
  CONSTRAINT TK_ORGANIZATION_WARRANTY_U01
  UNIQUE (CATEGORY_ID, ORGANIZATION_ID)
  USING INDEX DSS.TK_ORGANIZATION_WARRANTY_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.TK_ORGANIZATION_WARRANTY TO SELDATA;
