ALTER TABLE DSS.TK_PRODUCT_WARRANTY
 DROP PRIMARY KEY CASCADE;

DROP TABLE DSS.TK_PRODUCT_WARRANTY CASCADE CONSTRAINTS;

CREATE TABLE DSS.TK_PRODUCT_WARRANTY
(
  LINEID             NUMBER,
  OPERATING_UNIT     NUMBER,
  ORGANIZATION_ID    NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  PRODUCT_CODE       VARCHAR2(40 BYTE),
  WARRANTY_SEQ       NUMBER,
  CREATE_DATE        DATE,
  CREATE_BY          VARCHAR2(50 BYTE),
  ACTIVE             CHAR(1 BYTE),
  ATTRIBUTE1         VARCHAR2(100 BYTE),
  ATTRIBUTE2         VARCHAR2(100 BYTE),
  ATTRIBUTE3         VARCHAR2(100 BYTE),
  ATTRIBUTE4         VARCHAR2(100 BYTE),
  ATTRIBUTE5         VARCHAR2(100 BYTE),
  ATTRIBUTE6         VARCHAR2(100 BYTE),
  ATTRIBUTE7         VARCHAR2(100 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DSS.TK_PRODUCT_WARRANTY_PK ON DSS.TK_PRODUCT_WARRANTY
(LINEID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DSS.TK_PRODUCT_WARRANTY_U01 ON DSS.TK_PRODUCT_WARRANTY
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE AXM_TS_WMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DSS.TK_PRODUCT_WARRANTY ADD (
  CONSTRAINT TK_PRODUCT_WARRANTY_PK
  PRIMARY KEY
  (LINEID)
  USING INDEX DSS.TK_PRODUCT_WARRANTY_PK
  ENABLE VALIDATE,
  CONSTRAINT TK_PRODUCT_WARRANTY_U01
  UNIQUE (ORGANIZATION_ID, INVENTORY_ITEM_ID)
  USING INDEX DSS.TK_PRODUCT_WARRANTY_U01
  ENABLE VALIDATE);

GRANT SELECT ON DSS.TK_PRODUCT_WARRANTY TO SELDATA;
