DROP TABLE DSS.VIJ1 CASCADE CONSTRAINTS;

CREATE TABLE DSS.VIJ1
(
  OPERATINGUNIT      NUMBER,
  ORGANIZATIONID     NUMBER,
  ORGANIZATION_NAME  VARCHAR2(200 BYTE),
  BRAND              VARCHAR2(40 BYTE),
  BRANDDESC          VARCHAR2(200 BYTE),
  BASEBRAND          VARCHAR2(100 BYTE),
  MODEL              VARCHAR2(40 BYTE),
  MODELDESC          VARCHAR2(200 BYTE),
  CAT                VARCHAR2(40 BYTE),
  CATEGORY           VARCHAR2(200 BYTE),
  SCAT               VARCHAR2(40 BYTE),
  SCATEGORY          VARCHAR2(200 BYTE),
  SSCAT              VARCHAR2(40 BYTE),
  SSCATEGORY         VARCHAR2(200 BYTE)
)
TABLESPACE AXM_TS_WMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
