DROP TYPE DSS.REC_DATA_VALIDATION;

CREATE OR REPLACE TYPE DSS.REC_DATA_VALIDATION  AS OBJECT
(
   OPERATING_UNIT NUMBER,
   ORGANIZATION_ID NUMBER,
   LOCATION_CODE VARCHAR2 (100),
   PRODUCT_CODE VARCHAR2 (100),
   CUSTOMER_ID VARCHAR2 (100),
   CUSTOMER_SIDEID VARCHAR2 (100),
   QTY NUMBER,
   DESCRIPTION VARCHAR2 (200),
   OLDVALUE1 VARCHAR2 (200),
   OLDVALUE2 VARCHAR2 (200),
   STATUS CHAR (1),
   STATUS_MESSAGE VARCHAR2 (100),
   RECORDS NUMBER
)
/
