DROP TYPE DSS.REC_DATA_TAX_VALIDATION;

CREATE OR REPLACE TYPE DSS."REC_DATA_TAX_VALIDATION"                                          AS OBJECT
(
  OPERATING_UNIT NUMBER,
   ORGANIZATION_ID NUMBER,
   LOCATION_CODE VARCHAR2 (100),
   TAX_RATE_ID NUMBER,   
   TAX_RATE_NAME VARCHAR2 (100),
   TAX_COUNTRY_CODE VARCHAR2 (100),
   PRODUCT_CODE VARCHAR2 (100),
   ATTRIBUTE21 VARCHAR2 (100),
   ATTRIBUTE22 VARCHAR2 (100),
   STATUS CHAR (1),
   STATUS_MESSAGE VARCHAR2 (100),
   TAX_VALUE NUMBER,   
   TAX_PERCENATGE NUMBER,   
   RECORDS NUMBER
);
/
