DROP TYPE DSS.TYP_VAL_LOCATIONS;

CREATE OR REPLACE TYPE DSS.TYP_VAL_LOCATIONS AS OBJECT
(
   OPERATING_UNIT NUMBER,
   ORGANIZATION_ID NUMBER,
   LOCATION_CODE VARCHAR2 (10 BYTE),
   LocationName VARCHAR2 (200 BYTE),
   STATUS CHAR (1),
   STATUSMESSAGE VARCHAR2 (200 BYTE)
)
/
